### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by picosam** [richnologies/ngx-stripe#1]
Thank you for publishing this! May I use this to integrate Stripe Elements to my Angular 4 app? I suppose you do not use jQuery anywhere in your library?

**Comment by richnologies** [comment]
Thanks! No, there is not extra dependencies, just Angular. If you have any trouble using the library please let me know.

**Comment by picosam** [comment]
Thank you! In your README file, the following line doesn't make sense to me. May you please explain it?
`const name = this.stripeTest.get('name').value;`

Firstly, `stripeTest` does not exist. Second, which name are you trying to get, the cardholder's name?
