### ISSUE TITLE
onCard Example

### ISSUE THREAD

**Issue by simonaberry** [richnologies/ngx-stripe#10]
can you provide a quick example of how to use onCard. I have tried :

`<ngx-stripe-card [options]="cardOptions" [elementsOptions]="elementsOptions" (onCard)="card"></ngx-stripe-card>`

But this.card is empty when I try create the token

**Comment by ericuldall** [comment]
I was able to get the following working...

In my Component.ts:
```
  onCardChange(event) {
    console.log(event);
  }
```

In my Component.html:
```
<ngx-stripe-card [options]="stripeCardOptions" [elementsOptions]="elementsOptions" (onCard)="onCardChange($event);"></ngx-stripe-card>
```

**Comment by richnologies** [comment]
Thanks @ericuldall for the answer. Be aware that since version 0.5.1 the event is now (card) to align with the angular styleguide
