### ISSUE TITLE
 ngx-stripe-card now requires elementsOptions and options to render? 

### ISSUE THREAD

**Issue by hisham** [richnologies/ngx-stripe#101]
**Is this a feature request or a bug report?**
Bug report

**What's gone wrong?**
I'm upgrading to the latest and ngx-stripe-card won't render the stripe element. 

**Steps to reproduce**

Try: 

` <ngx-stripe-card></ngx-stripe-card>`

**Other information**

It only renders if I pass `[options]="cardOptions" [elementsOptions]="elementsOptions"`. Is this expected behaviour? It wasn't like this in version 9.

**Comment by richnologies** [comment]
Hi @hisham, thanks for the report. 
It's not the expected behavior. We are working to fix this. I'll update this issue when the fix is released.

**Comment by richnologies** [comment]
Hi @hisham,

We just release a new version `10.1.1` that I think will solve this bug. Please let me know if it works for you.

Thanks,

R

**Comment by hisham** [comment]
It's looking good now! Thank you @richnologies :)
