### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by worthy7** [richnologies/ngx-stripe#108]
If you are going to introduce breaking changes please up the major version number on the npm package

https://semver.org/

**Comment by richnologies** [comment]
Thanks for the link. I know how semver works, that why I've added a big notice in the readme:

https://github.com/richnologies/ngx-stripe#notice

And a very detailed information about which version you need:

https://richnologies.gitbook.io/ngx-stripe/getting-started/installation

I'm very sorry about any inconvenience, but it was the only way I've found to keep to lines of versions (lts and legacy) for each angular major. 

Again, so sorry about any trouble. 

R
