### ISSUE TITLE
Card Info Valid output

### ISSUE THREAD

**Issue by simonaberry** [richnologies/ngx-stripe#11]
is there a way to determine if the card information is valid ? I wish to disable the buy button until such time.

**Comment by picosam** [comment]
I think there's a CSS class that's automatically set when you're typing the card info.

**Comment by simonaberry** [comment]
but the button that I want to disable is outside the stripe iframe... are you saying the ngx-strip component will emit a class ?

**Comment by picosam** [comment]
No, in that case I take my words back!

**Comment by richnologies** [comment]
If you use the elements.create method like in the first example in the readme, then the card object has a: card.on('change', cb) method, so you disable the button. If you are using the ngx-stripe-card component, you can't access that by now, but I will soon add an output to allow to subscribe to that event stream.

`
card.on('change', function(event) {
  if (event.error) {
    errorElement.textContent = event.error.message;
    errorElement.classList.add('visible');
  }
});
`

**Comment by ericuldall** [comment]
@richnologies Your example seems to fail with the following error:
```
 Argument of type '(event: any) => void' is not assignable to parameter of type '() => void'.
```
Any insight on how to resolve this?

**Comment by lukaVarga** [comment]
Any news regarding this @richnologies ? TS won't compile and, as far as I know, there is no other way to catch errors before the user tries to submit the form.

**Comment by smlee** [comment]
For the eventlisteners you can just create a function and use bind to pass in _this_

example:

`this.cardNumber.on('change', this.onChange.bind(this));

onChange(event) {
    console.log(event);
    if (event && !!event.error) {
      this.errorMessage = event.error.message;
    } else {
      this.errorMessage = '';
    }
    this.cdr.detectChanges();
  }`

**Comment by richnologies** [comment]
Hi, sorry for the delay, I believe his error is solved now, if anyone have any more problems about this, can always reopen

**Comment by jorgeartigas** [comment]
What about if we are using the ngx-stripe-card component, is there any way to determine if the information is valid, before clicking buy?

**Comment by evaletolab** [comment]
this one,
```js
        this.card = this.elements.create(...);
        this.card.addEventListener('change', (event)=> {
          // use it in template [disabled]="!isValid"
          this.isValid=event.complete;
        });
```

**Comment by DwieDima** [comment]
I also had to strugge with this to set my button disabled.
This is my workaround:

```
  @ViewChild(StripeCardNumberComponent) number: StripeCardNumberComponent;
  @ViewChild(StripeCardExpiryComponent) expiry: StripeCardExpiryComponent;
  @ViewChild(StripeCardCvcComponent) cvc: StripeCardCvcComponent;
  public isValid = false;

...
```

```
ngOnInit() {
    const number$ = fromEvent(this.number.element as any, 'change');
    const expiry$ = fromEvent(this.expiry.element as any, 'change');
    const cvc$ = fromEvent(this.cvc.element as any, 'change');

    combineLatest([number$, expiry$, cvc$])
      .pipe(
        map(([number, expiry, cvc]: any) => {
          return (
            !!!number.error &&
            number.complete &&
            !!!expiry.error &&
            expiry.complete &&
            !!!cvc.error &&
            cvc.complete
          );
        }),
        tap((isValid) => (this.isValid = isValid))
      )
      .subscribe();
}
```

```
    <button [disabled]="!isValid" (click)="onAddCreditCard()"
      >save</button
```
