### ISSUE TITLE
How do I access all element component with version v7-lts / 7.5.x+?

### ISSUE THREAD

**Issue by saascharge** [richnologies/ngx-stripe#112]
I am stuck with version v7-lts / 7.5.x+ at the moment.

I need to modify the layout the payment page and essentially need to achieve something like this:
https://stripe.dev/elements-examples

So I need to access the mount & registerElements methods of the element. How can I do that?

It seems to me that <ngx-stripe-card-expiry>, <ngx-stripe-card-cvc> would be ideal but they must only be available in a later version?

**Comment by richnologies** [comment]
Hello @saascharge,

Actually this scenario was the first supported by the library and specific components for the different payments method has been added after. But in the order to provide the simpler possible experience those components get more popular. 

I create a new section in the docs explaining how to manually register and mount elements:
https://richnologies.gitbook.io/ngx-stripe/core-concepts/manually-mount-your-element

Please let me know if these works for you. Maybe we can give it more relevance in the docs.

Thanks for the feedback 👍

R
