### ISSUE TITLE
Bug in gitbook sample code for Payment Request Button

### ISSUE THREAD

**Issue by ntziolis** [richnologies/ngx-stripe#114]
The sample code provided is not correct. It took us a while to figure out that there is no payment event on the `gx-stripe-payment-request-button`

Instead of:
```ts
(payment)="onPaymentMethod($event)"
```
it should be:
```ts
(paymentMethod)="onPaymentMethod($event)"
```

Otherwise it worked like a charm, great work!

Link to the page in question:
https://richnologies.gitbook.io/ngx-stripe/core-concepts/payment-request-button

Screenshot to the section inquestion:
![image](https://user-images.githubusercontent.com/265338/96366227-78fa8900-1146-11eb-9652-39bb82b40bfd.png)

**Comment by richnologies** [comment]
Hi @ntziolis, thanks for the issue. Docs updated 👍
