### ISSUE TITLE
ngx-stripe-card is not a known element

### ISSUE THREAD

**Issue by Rui90** [richnologies/ngx-stripe#115]
I'm trying to use ngx-stripe on my angular solution and I've followed everything on the tutorial

But when I'm trying to set an example:

```
  <h2>Create Token Example</h2>
    <ngx-stripe-card
    [options]="cardOptions"
    [elementsOptions]="elementsOptions"
    ></ngx-stripe-card>
    <button type="submit" (click)="createToken()">
    CREATE TOKEN
    </button>
```

I am getting 
![image](https://user-images.githubusercontent.com/6035220/96609489-7d63a500-12f2-11eb-9245-7509b78f17db.png)

Any idea why?

My **app.module**

```
@NgModule({
  declarations: [AppComponent],
  imports: [
    I18NextModule.forRoot(),
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    NgbModule,
    NgxStripeModule.forRoot("key"),
  ],
  providers: [I18N_PROVIDERS],
  bootstrap: [AppComponent]
})
```

**Comment by medy36** [comment]
i'm getting this error too. any idea?

**Comment by akshaysethia** [comment]
Even I am facing the same issue, don't know its origin,

**Comment by GertjanJ** [comment]
Facing the same issue with angular 11

"dependencies": {
    "@angular/animations": "~11.0.1",
    "@angular/common": "~11.0.1",
    "@angular/compiler": "~11.0.1",
    "@angular/core": "~11.0.1",
    "@angular/forms": "~11.0.1",
    "@angular/localize": "~11.0.1",
    "@angular/platform-browser": "~11.0.1",
    "@angular/platform-browser-dynamic": "~11.0.1",
    "@angular/platform-server": "~11.0.1",
    "@angular/router": "~11.0.1",
    "@stripe/stripe-js": "^1.11.0",
    "ngx-stripe": "^10.1.2",
  },

**Comment by GertjanJ** [comment]
So the issue was that the component was not available in a child module. Adding "NgxStripeModule.forChild()" resolved the issue

**Comment by knowledgeplaces** [comment]
I have still the issue even adding the NgxStripeModule.forChild().
In my template, the ngx-stripe-card has the following error:
Can't bind to 'elementsOptions' since it isn't a known property of 'ngx-stripe-card'.
Any advice appreciated.

**Comment by MohitMishraFalna** [comment]
https://github.com/richnologies/ngx-stripe/issues/163
If you facing this issue still so I have a solution this works for me. If you use lazy loading in your project so please check the routing. I am facing same issue last two days but i never got any solution from the net which could help me, I did all things, then I checked my routing and there was some issue. Please Check the Routing.

Now my project run perfectible.
