### ISSUE TITLE
error TS2300: Duplicate identifier 'CancellationReason'

### ISSUE THREAD

**Issue by CabelDhojShrestha** [richnologies/ngx-stripe#117]
**Is this a feature request or a bug report?**
This is a bug report.

**What's gone wrong?**
I have been using ngx-stripe (^9.2.0) with stripe-js (^1.9.0) in the development process for an ionic app. All seemed to be working till last night. I am running into issues running the app today. Bunch of similar errors are shown:

ERROR in node_modules/@stripe/stripe-js/types/api/paymentintents.d.ts:115:10 - error TS2300: Duplicate identifier 'CancellationReason'.
[ng] 115     type CancellationReason =
[ng]              ~~~~~~~~~~~~~~~~~~
[ng]   node_modules/@stripe/stripe-js/types/api/PaymentIntents.d.ts:115:10
[ng]     115     type CancellationReason =
[ng]                  ~~~~~~~~~~~~~~~~~~
[ng]     'CancellationReason' was also declared here.

**What was meant to happen?**
The app should have loaded without any problems.

**Steps to reproduce**'
In an Angular9 ionic mobile app project,
Import StripeCardComponent, StripeService from ngx-stripe (^9.2.0)
Import StripeCardElementOptions, StripeElementsOptions from @stripe/stripe-js (^1.9.0)

and execute 'ionice serve --lab' to run the app. 

**Other information**

macOS, npm (6.14.7), node (v14.9.0)

**Comment by richnologies** [comment]
Hi @CabelDhojShrestha, thanks for the issue, very will detailed. It seems to be a problem with @stripe/stripe-js package. Could you please indicate me the exact version of `@stripe/stripe-js` you're using so I can try to replicate the issue. Thanks :)

**Comment by CabelDhojShrestha** [comment]
Hi Ricardo,

Here are the couple of initial lines in the package.json of @stripe/stripe-js in my node-modules
`"_from": "@stripe/stripe-js@^1.9.0",
  "_id": "@stripe/stripe-js@1.11.0",
  "_inBundle": false,
  "_integrity": "sha512-SDNZKuETBEVkernd1tq8tL6wNfVKrl24Txs3p+4NYxoaIbNaEO7mrln/2Y/WRcQBWjagvhDIM5I6+X1rfK0qhQ==",
  "_location": "/@stripe/stripe-js",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "@stripe/stripe-js@^1.9.0",
    "name": "@stripe/stripe-js",
    "escapedName": "@stripe%2fstripe-js",
    "scope": "@stripe",
    "rawSpec": "^1.9.0",
    "saveSpec": null,
    "fetchSpec": "^1.9.0"
  },`

**Comment by CabelDhojShrestha** [comment]
@richnologies 
This is what looks to be the culprit. I have a function to return the observable from the stripeService, like so.

L1: getToken() {
L2:    const name = this.formGroup.get('name').value;
L3:    return this.stripeService.createToken(this.stripeCard.element, {name});
L4: }

I am not sure why L3 is problematic.

**Comment by CabelDhojShrestha** [comment]
@richnologies What worked for me was adding the following in the 'compilerOptions' in my tsconfig.json file.
"skipLibCheck": true

I'm not sure that's a good fix though. Please let me know if there's a better resolution for this.

**Comment by alphacentauridigital** [comment]
Hi @CabelDhojShrestha 

Please check the following link It will explain the pros and cons of SkipLibCheck.

https://dd.engineering/blog/typescript-the-skiplibcheck-option-explained

**Comment by CabelDhojShrestha** [comment]
@alphacentauridigital Thanks! That was helpful.
