### ISSUE TITLE
Create Subscription

### ISSUE THREAD

**Issue by vandanachadha** [richnologies/ngx-stripe#12]
Can I create subscriptions using this package? 
On trying the following:
		  //create subscription
			this.stripeService.subscriptions.create({
			  customer: result.token.id,

, am getting this error:
Property 'subscriptions' does not exist on type 'StripeService'.

**Comment by richnologies** [comment]
I've cheked the Stripe docs about subscriptions, but it seems to be a server task, not for the browser. As long as I get, you get the token as usual, create the customer and then the subscriptions. 

Please, point me to the docs where it explains how to create subscriptions, and I will try to add this feature

**Comment by mo2menelzeiny** [comment]
@richnologies https://stripe.com/docs/api/node#create_subscription

**Comment by ospaarmann** [comment]
@vandanachadha The workflow to create a subscription is as follows:

**Frontend using this package:**

- Collect payment and customer details using Elements (credit card or bank account)
- Create a Source (https://stripe.com/docs/stripe-js/reference#stripe-create-source)
- Send Source + collected customer info to your backend

**Backend, however you implement it:**

- Backend creates customer with source by calling Stripe API (https://stripe.com/docs/sources/customers)
- Subscribe customer to a plan (https://stripe.com/docs/api#create_subscription)

**Comment by richnologies** [comment]
As @ospaarmann the create subscription is part of the server workflow, so out of the scope of this package.
