### ISSUE TITLE
New version of module "@stripe/stripe-js" has no exported member 'CanMakePaymentResult'

### ISSUE THREAD

**Issue by kivinm** [richnologies/ngx-stripe#121]
@stripe/stripe-js was updated yesterday to version 1.12.0
And it has no 'CanMakePaymentResult' class anymore.
So ngx-stripe now gives an error during production build:

ERROR in node_modules/ngx-stripe/lib/components/payment-request-button.component.d.ts:3:88 - error TS2305: Module '"@stripe/stripe-js"' has no exported member 'CanMakePaymentResult'.

**Comment by levarberry** [comment]
downgrade to 1.11.0

**Comment by BruneXX** [comment]
Downgrading to v1.11.0 works for me

**Comment by hofman-stripe** [comment]
We just published v1.12.1 that should fix this issue. Sorry about this.

**Comment by BruneXX** [comment]
Thanks @hofman-stripe I'll try it right now
