### ISSUE TITLE
Question. Can I make receipts from a sale?

### ISSUE THREAD

**Issue by ceszgdav** [richnologies/ngx-stripe#127]
More than an issue, is a question.. can I make charges from a sale with this package? I mean, for a example is that if you subscribe to my service, you can rent 3 cars for 9.99 but if you want you can add 1 or 2 more cars by 3.99 extra per car, I want to know if I can make the charge for that extra with ngx-stripe

and if the answer is yes... how can I make this extra charge? 

thanks for the support!

**Comment by richnologies** [comment]
Hi @ceszgdav, happy to help

I'd need more info to give a more concrete answer, but based on what you told me I can think of two cases:

1) **The 9.99 for the 3 cars a is subscription and now you want to update it to a 13.98 subscription with one extra card or 17.97 for two**. In this, I think what you're looking for a subscription update. That is a back-end change, so is out of the scope of ngx-stripe. You can see the docs here: https://stripe.com/docs/api/subscriptions/update. You can add the extra charges as new items to your subscription. The price_data parameter allows you to use prices that are no necessary defined in the plans.

2) **You charge the user for 9.99 and now you want to charge the extra amount**. If you're using Payment Intents to collect the payment method information, for example a credit card, you can use the setup_future_usage param when you create the intent: https://stripe.com/docs/api/payment_intents/create. This allows you to use the payment method for future payments. If you also add the off_session param you will be able to charge without the presence of the user. This depends on your flow. Here is a link to the official docs on best practices for future usage: https://stripe.com/docs/payments/payment-intents#future-usage. Again, creation of the payment intent is a back-end task, so out of the scope of this library.

In any case, even if its not a ngx-stripe related thing, I'm happy to help. If you still have question, please let me know. 

R
