### ISSUE TITLE
How to customize credit card form in Stripe?

### ISSUE THREAD

**Issue by jstechaut** [richnologies/ngx-stripe#128]
To style stripe element with the first-line card number and second-line CVC and expiry date
![Screenshot 2021-04-22 125149](https://user-images.githubusercontent.com/59908497/115674678-8863c480-a36b-11eb-8050-fe14b946346e.png)

**Comment by richnologies** [comment]
Hey @jstechaut,

`Stripe elements` are styled using a Style object, which consists of CSS properties. Here is a link to the `Stripe JS reference` for [Style](https://stripe.com/docs/js/appendix/style) with more details.

In `ngx-stripe` you can do it in a similar way, here is link to the [styling](https://richnologies.gitbook.io/ngx-stripe/core-concepts/styling) docs section.

Finally, here is a link to the stripe elements [examples](https://stripe.dev/elements-examples/). The code is open source so it may help you get some inspiration. 

Thank for getting in touch.

R
