### ISSUE TITLE
Unrecognized create() parameter

### ISSUE THREAD

**Issue by elfoxus** [richnologies/ngx-stripe#132]
Hi, I am currently on version 11. I have some problem with creating stripe card components(number, expiry date, cvc). What I see in console is message `Unrecognized create() parameter: classes.webkitAutoFill is not recognized parameter. (..)`. What can I do with this problem?
Thanks.

**Comment by richnologies** [comment]
Hi @elfoxus,

Happy to help you, but I'm going to need more info on how are creating and mounting your components. If you can provide me with an example of the issue I will try to fix it. For example here is a Stackblitz example running a very simple card that just creates a token:

https://stackblitz.com/edit/ngx-stripe-issue-132?devtoolsheight=33&file=src/app/app.component.ts

Maybe you can fork it and make some changes so it's similar to what you have. Minimal example that causes the error will be more that enough

Thanks,

R

**Comment by elfoxus** [comment]
First of all, thank you for quick reponse.

What I am about is this fragment of code:
``` cardOptions: StripeCardElementOptions = {
    classes: {
      webkitAutofill: 'StripeElement--webkit-autofill'
    },
    style: {
      base: {
        iconColor: '#666EE8',
        color: '#31325F',
        fontWeight: '300',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSize: '18px',
        '::placeholder': {
          color: '#CFD7E0'
        }
      }
    }
  };
  ```
  
I did not provide this, so I see some error in console
```classes: {
      webkitAutofill: 'StripeElement--webkit-autofill'
    },
    ```

But still where is this class coming from? I am missing something here.

**Comment by richnologies** [comment]
My fault, I just put that code because I thought you had. This options come from here:

https://stripe.com/docs/js/elements_object/create_element?type=card#elements_create-options-classes-webkitAutofill

You can add specific classes but is no necessary. If you check that stackblitz like again, you'll see I've removed that class and still no console errors

**Comment by elfoxus** [comment]
I see. 
I'm almost done doing my example, I will provide it in few minutes.

**Comment by elfoxus** [comment]
https://stackblitz.com/edit/ngx-stripe-issue-132-expnpx?file=src/app/app.component.ts
