### ISSUE TITLE
ACH Payments

### ISSUE THREAD

**Issue by vijaypp01** [richnologies/ngx-stripe#137]
**Is this a feature request or a bug report?**
No

**What's gone wrong?**
Are there any development going on for the bank transfer module

We are looking for modules that support both credit card and bank transfers with instant verification.

**Comment by richnologies** [comment]
Hi @vijaypp01, here is a link to the docs for ACH payments with Stripe: https://stripe.com/docs/ach

Be aware is only supported for businesses based in the U.S. 

Personally I live in Europe, so I use SEPA Direct Debit but it works nicely. I have integrations charging both credit cards and bank accounts. 

Please let me know if you have further questions 

R
