### ISSUE TITLE
How to use Stripe apiKey, if I am getting it from API Call

### ISSUE THREAD

**Issue by imraqes** [richnologies/ngx-stripe#14]
Hi

I am receiving Stripe apiKey from a http call on checkout page, how to use it  from there in `forRoot('apiKey').`

**Comment by AlexHenkel** [comment]
+1

**Comment by richnologies** [comment]
Hi @imraqes and @AlexHenkel, sorry for the delay. Take a look at the new StripeFactoryService in the readme, I think it solves your case
