### ISSUE TITLE
StripeCardComponent doesn't use input options on initialization

### ISSUE THREAD

**Issue by Nitro-N** [richnologies/ngx-stripe#141]
https://github.com/richnologies/ngx-stripe/blob/41eeb79db90be551f0d313d1d37a372a2c93331d/projects/ngx-stripe/src/lib/components/card.component.ts#L88
https://github.com/richnologies/ngx-stripe/blob/41eeb79db90be551f0d313d1d37a372a2c93331d/projects/ngx-stripe/src/lib/components/card.component.ts#L90

**Comment by richnologies** [comment]
Hi @Nitro-N, I had a quick look and I think you're right. I will make some tests after work today and very likely I will do a new release fixing this issues. 

Thanks for reporting

R
