### ISSUE TITLE
Card Group icon card

### ISSUE THREAD

**Issue by Marius-Romanus** [richnologies/ngx-stripe#142]
Hi, is it possible to put the animated icon of the card with ngx-stripe-card-group?
Thanks

**Comment by richnologies** [comment]
Hi @Marius-Romanus,

I don't how I miss this issue, I'm really sorry. I'm sure you already figure it out, but just in case here is a stackblitz:

https://stackblitz.com/edit/ngx-stripe-issue-142

Basically the `ngx-stripe-card-number` accepts an option named `showIcon` that is a boolean (false by default). 

Kind regards

R

**Comment by Marius-Romanus** [comment]
Great, thank you very much! :)
