### ISSUE TITLE
Show ng-content during loading

### ISSUE THREAD

**Issue by AadamZ5** [richnologies/ngx-stripe#145]
**Is your feature request related to a problem? Please describe.**
The Stripe Elements take a (usually short, but possibly long) moment to load a secure connection using Stripe's proprietary process. This of course means that there is a delay between Angular's component creation, and the actual Stripe Elements being displayed. I was hoping that there would be some easy way to show a loading state _without_ making extra templates and variable logic on my end. 

I know that the component offers it's current state, and observable events too, but I was hoping for an easy, implicit, and inline solution.

**Describe the solution you'd like**
The solution I was thinking of was simply to forward the content inside of the `<ngx-stripe-card>` tag to the template using `<ng-content>`

Here's an example:

In my code:
```html
...

  <ngx-stripe-card [elementsOptions]="stripeElementsOptions" [options]="stripeOptions">
    Loading card input...
  </ngx-stripe-card>

...
```

In the `NgxStripeCard` component:
```typescript
@Component({
  selector: 'ngx-stripe-card',
  template: `
    <ng-template #content>
      <ng-content></ng-content> <!-- <== Notice here the content projection -->
    </ng-template> 

    <div class="field" #stripeElementRef>

      <!-- See this issue about why this isn't simpler: https://github.com/angular/angular/issues/22972#issuecomment-461375621-->
      <!-- The "Loading card input..." string would end up here while the status is not 'ready' -->
      <ng-container *ngTemplateOutlet="status !== 'ready' ? content : null"></ng-container> 

    </div>
  `
})
export class StripeCardComponent implements OnInit, OnChanges, OnDestroy {
  
  ...

}
```

Take a look here for more Angular documentation: https://angular.io/guide/content-projection#single-slot-content-projection

**Describe alternatives you've considered**
A more versatile but less implicit (and less hacky) solution would be to have an `@Input()` that accepts a `TemplateRef` to display during loading.

And perhaps a barebones solution would be an `@Input()` that accepts just a string to display while loading.

**Additional context**
I've got a lot of form inputs where my instance of `NgxStripeCard` lives, and I commonly try to make it look like one of the other form fields. Making an extra loading template and logic for it is just extra clutter in my component, and I would love if I could leave that abstracted away. I think this approach is particularly fitting here because there is really no other purpose for the contents inside the `<ngx-stripe-card></ngx-stripe-card>` tags. This would be an awesome improvement in my opinion.

What are your thoughts?

**Comment by richnologies** [comment]
Hi @AadamZ5,

Thanks for the suggestion, I really like it. (N



```html
<ngx-stripe-card [options]="cardOptions">
  <span *ngxStripePreloader>Loading Stripe Card...</span>
</ngx-stripe-card>
```

Kind regards,

R

**Comment by AadamZ5** [comment]
That's a wonderful solution! I forgot about the child-directive approach. I think your solution is the most elegant and flexible way to solve this.

So I assume you'll be using something like [`@ContentChild(<future-directive-name>)`](https://angular.io/api/core/ContentChild) to capture the loading content marked with the directive?

Also, what is your rationale for using the word "Preloader" in the directive? The way I see it, the content we're supplying isn't necessarily pre-loading anything, it is just being displayed _while_ loading. Can I offer the names `*ngxStripeLoading` or even `*ngxStripeLoadingTemplate`? What are your thoughts?

**Comment by richnologies** [comment]
@AadamZ5, you're right, we are going with the `@ContentChild` and you're also right about the the name. We will use the `*ngxStripeLoadingTemplate`.

Like I've said, I will put a PR together with this feature for all HTML elements. You feedback and comments on that PR will be hight appreciate it
