### ISSUE TITLE
Support the new Payment Element API

### ISSUE THREAD

**Issue by yharaskrik** [richnologies/ngx-stripe#147]
**Describe the solution you'd like**
Support Stripes new feature for Payment Element, the all in one payment method element for all stripe supported payment methods

**Describe alternatives you've considered**
implementing each one individually

**Additional context**
https://stripe.com/blog/introducing-the-payment-element

**Comment by yharaskrik** [comment]
Nice! Thank you!

**Comment by aelmod** [comment]
Hello. Any updates?

**Comment by fmendoza** [comment]
> Any updates?

It's already implemented.

**Comment by richnologies** [comment]
As @fmendoza says, is already implemented. I've added a new page to the docs site on how to use it. But as usual the idea is to try to keep it as close as possible to the StripeJS API. I will close this issue new but if you found any issues using the new component, feel free to open a new one 

https://docs.ngx-stripe.dev/core-concepts/payment-element
