### ISSUE TITLE
Able to inject custom payment method

### ISSUE THREAD

**Issue by Salvatore-Als** [richnologies/ngx-stripe#151]
**Describe the solution you'd like**
It would be nice to be able to inject different payment methods into the stripe template.

**Additional context**
![image](https://user-images.githubusercontent.com/58212852/139878931-800040d2-fcde-4986-81f0-7eb1d36a3542.png)

**Comment by richnologies** [comment]
Hi @Salvatore-Als,

Could you elaborate a bit more on this idea. Are you suggesting being able to add extra payment methods not supported by Stripe?

**Comment by richnologies** [comment]
Hi @Salvatore-Als,

I can see how that could be very useful, but we have two problems:

1. `ngx-stripe` is just a wrapper around StripeJS and we try to stay as align with them as possible to provide a consistent experience. This feature is a bit outside the scope of the library. 
2. The content of the Payment Element is controlled by Stripe. Is basically an iframe, we can't add any tabs or content. 

However, Stripe might be taken steps on that direction, check this out: stripe/stripe-js@524dc2d

They are already working on a PayPal integration or so it seems.

Sorry I can't give you a better answer right now

Kind regards

R
