### ISSUE TITLE
Dependency angular/common@13.0.0

### ISSUE THREAD

**Issue by mbagiella** [richnologies/ngx-stripe#154]
Error when trying to upgrade to Angular 13

npm ERR! Found: @angular/common@13.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer **@angular/common@">=9.0.0 <13.0.0"** from ngx-stripe@12.7.1
npm ERR! node_modules/ngx-stripe
npm ERR!   ngx-stripe@"^12.7.1" from the root project

**Comment by richnologies** [comment]
Hi @mbagiella, thanks for the feedback

A new version `13.0.0` has been release with the dependencies updated. That should fix this issue.

Feel free to open this issue if the problem persists.

R
