### ISSUE TITLE
[BUG] card icon not loading correctly

### ISSUE THREAD

**Issue by jrywin** [richnologies/ngx-stripe#157]
**Describe the bug**
Hello,
Im trying add card icon to ngx-stripe-card-number element.

My options:

 cardNumberOptions: StripeCardElementOptions = {
    hideIcon: false,
    iconStyle: 'solid',
    style: {
      base: {
        fontWeight: '600',
        iconColor: '#e0e0e0',
        fontSize: '17px',
        fontFamily: 'Open Sans',
        '::placeholder': {
          color: '#e0e0e0',
        }
      }
    }
  }

How i init a cardNumberElement:

  <ngx-stripe-card-number [options]="cardNumberOptions"> </ngx-stripe-card-number>

So now CardNumberElement is showing on my page but it miss card icon.

I've got log in console:

![obraz](https://user-images.githubusercontent.com/46504128/143526330-bef66c6f-1d3e-47a0-b66e-d5722bdcce9c.png)

StripeVersion: "1.21.1
Angular: 8
ngx-stripe: 9.3.0 (tried on ver 8 too)

What im doing wrong?

**Comment by richnologies** [comment]
Hi @jrywin, check this StackBlitz example, it's not exactly your case, but it's close

StripeCardElementOptions is for the card element, you have a more specific interface StripeCardNumberElementOptions that includes a property called `showIcon`

Seems to me the if you replace `hideIcon` for `showIcon` it should work for you

https://stackblitz.com/edit/ngx-stripe-issue-142

Hope this helps, please let me know if this works for you

Kind regards

R

**Comment by jrywin** [comment]
Works perfect!
