### ISSUE TITLE
[BUG] Payment Element not showing up on the UI

### ISSUE THREAD

**Issue by jaurakunal** [richnologies/ngx-stripe#161]
**Describe the bug**
Trying to use the `Payment Element` to integrate with Stripe - 90% of the times the `Payment Element` won't show up on the UI. 

Using the browser's `element inspector` shows that the `iframe` used by the `<ngx-stripe-payment>` component has an inline `style` property that is setting the height to `2px`

**To Reproduce**
1. Follow the `payment-element` [docs](https://docs.ngx-stripe.dev/core-concepts/payment-element) to setup checkout page
2. Navigate to ui

**Expected behavior**
The payment element showing a form accept card payment should show up

**Screenshots**
* This is how the UI shows up
![Stripe_iframe_without-manual-changes](https://user-images.githubusercontent.com/12739201/149897496-ee459b6d-c04d-428e-8a0e-59235df59669.png)

* This is how it shows once I manually update the height

![Stripe_iframe_manually-set-height](https://user-images.githubusercontent.com/12739201/149897682-264c8080-7653-4895-a7c9-9ec93c095abf.png)

**Desktop (ple
ase complete the following information):**
 - OS: Win 10 Pro
 - Browser: Chrome
 - Version: 97.0.4692.71 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
I've checked and verified that the `clientSecret` returned from my server is correct and that the stripe session api call loads fine. In-fact, if i manually set the height of the iframe (from the browser element inspector) I'm able to complete the checkout process.

**Comment by jaurakunal** [comment]
Here's my angular template (`clientSecret` is set from the response to an HTTP call to my backend server)
```
      <mat-step [stepControl]="paymentDetailsFormGroup" editable="false">
        <form [formGroup]="paymentDetailsFormGroup">
          <ng-template matStepLabel>Payment Details</ng-template>

          <ng-container *ngIf="clientSecret !== ''">
            <ngx-stripe-payment [clientSecret]="clientSecret">
            </ngx-stripe-payment>
          </ng-container>
        </form>
        <div>
          <button mat-raised-button (click)="pay()" color="accent">Pay</button>
        </div>
      </mat-step>

```

And this is my `pay()` method:

```
  pay() {
    this.showLoader('Please wait while process your payment.')
    this.stripe.confirmPayment({
      elements: this.paymentElement.elements,
      confirmParams: {
        payment_method_data: {
          billing_details: {
            name: this.contactDetailsFormGroup.get('name').value
          }
        }
      },
      redirect: 'if_required'
    }).subscribe((result) => {
      if (result.error) {
        console.log(result.error.message);
        this.loader.dismiss();
        this.showAlertMessage(result.error.message);
      } else {
        if (result.paymentIntent.status === 'succeeded') {
          this.loader.dismiss();
          this.stepper.next();
        } else {
          console.log(result);
        }
      }
    });
  }

```

**Comment by richnologies** [comment]
Hi @jaurakunal, sorry about the delay, it's been a few crazy weeks for me. 

I don't know if you still need help, but at first sight it seems to me to be something related to how the stepper handles the height. Here is a minimal example on Stackblitz: https://stackblitz.com/edit/ngx-stripe-issue-161?file=src/app/app.component.ts

Maybe you can add the stepper, so we can replicate the behaviour. I'm happy to help you from there.  

King regards,

R

**Comment by ovideozn** [comment]
I'm also getting the exact same behaviour after updating from Angular 11 to Angular 13, ngx-stripe from 12.7.0 to 13.0.0 and @stripe/stripe-js from 1.20.3 to 1.25.0.

Please advise - I haven't been able to replicate in stackblitz so far.

**Comment by richnologies** [comment]
Hi @ovideozn, I've added the stepper to the example. The problem here is that the payment element is being "load" inside an step that is not visible, that is why it does not get the appropriate height. 

A workaround that I've found is to delay the initial load of the payment element until the user gets to the right step. 

I've have updated the example here: https://stackblitz.com/edit/ngx-stripe-issue-161?file=src/app/app.component.ts

We save the clientSecret in a new variable, but we only update `elementOptions.clientSecret` once we are in the right step. We control that with the `onSelectionChange`, so the *ngIf that controls the visibility of the element will only be true after we reach that step. 

A few things to notice:

- Once the element has been added to the DOM, you should not remove it, otherwise you will loose any information you already fill in, that is why we **DON'T** have something like: 
```
*ngIf="stepper.selectedIndex === 1 && elementsOptions?.clientSecret"
```
