### ISSUE TITLE
StripePaymentElementComponent seems to ignore the Elements Appearance API

### ISSUE THREAD

**Issue by knowledgeplaces** [richnologies/ngx-stripe#164]
I have setup a payment component with Angular 12 and ngx-stripe and everything works fine.
Now, I would like to use a theme to style my component, [as described here](https://stripe.com/docs/stripe-js/appearance-api).
Essentially, I would like to use a theme, and I wrote a code like this:
```
const stripeAppearance = { theme: 'flat' } as Appearance;
_this.elementsOptions = {
	clientSecret: _this.stripePaymentIntentResponse.paymentIntent.client_secret,
	appearance: stripeAppearance
};
```
When I run the app, no error in compile, no error in console, but the theme is not applied.
Please advise.

**Comment by gentildpinto** [comment]
I've the same issue
This ignores all stylization attempts, there is no way to change the elements. They look static, could you please fix this out?

**Comment by richnologies** [comment]
Hi @knowledgeplaces and @gentildpinto, I make a small change in the example and it seems to work fine: https://stackblitz.com/edit/ngx-stripe-issue-164 by passing the styles in the elements options, are you doing it like that?

**Comment by gentildpinto** [comment]
> Hi @knowledgeplaces and @gentildpinto, I make a small change in the example and it seems to work fine: https://stackblitz.com/edit/ngx-stripe-issue-164 by passing the styles in the elements options, are you doing it like that?

It doesn't work with `"ngx-stripe": "^9.0.5"`  on Angular v9
Maybe I Should update to Angular 12 and use `"ngx-stripe": "^13.0.0"` like in the example to work

**Comment by richnologies** [comment]
Ah!, yeah, sorry, I will update the older versions
