### ISSUE TITLE
StripePaymentInputComponent seems to ignore my css style

### ISSUE THREAD

**Issue by Lazaro-manuel** [richnologies/ngx-stripe#165]
I'm trying to add a style of mine to one of the stripe's input classes, and it seems that it is ignoring it, and I would like to know why this is happening.

**Comment by Lazaro-manuel** [comment]
I want to get any class name there to put my css style.

And I also want to style each entry, like card, cvc and expiry


  elementsOptions: StripeElementsOptions = {
    locale: 'pt',
    appearance:{
      theme: 'night',

      rules: {
        '.Input':{
          border: '6px solid #a85e32',
          padding: '0.375rem 0.75rem;',
          width: '100%',
          colorBackground: '#a85e32'
        }
      }
    }

  };

**Comment by Lazaro-manuel** [comment]
> Hi @Lazaro-manuel, I need more details, is this a payment element or a card element? Can you provide me a snippet of the code you've tried so far? both HTML and TS?

**Comment by richnologies** [comment]
Hi @Lazaro-manuel, I think is the same issue as this one: https://github.com/richnologies/ngx-stripe/issues/164
