### ISSUE TITLE
[BUG] Glitchy stripe element behaviour on android browsers

### ISSUE THREAD

**Issue by severmatej** [richnologies/ngx-stripe#166]
**Describe the bug**
When using separate stripe elements (ngx-stripe-card-number, ngx-stripe-card-expiry, ngx-stripe-card-cvc) there is a glitchy behaviour on mobile (chrome) browser. The placeholder / input text is pushed up and the virtual keyboard not always appears. Console logging focus event on each element shows occasional double events on one tap. The issue accures with or without added styles .

**To Reproduce**
1. Create new angular project
2. npm install ngx-stripe @stripe/stripe-js
3. Add all 3 elements within ngxStripeCardGroup directive
4. ng s --host 0.0.0.0
5.  Open project with Android chrome: <your-ip>:4200

**Expected behavior**
Tap on each element triggers focus once, which opens the virtual keyboard.

**Screenshots / Recordings**
https://user-images.githubusercontent.com/91458884/161518011-d918f3e2-bbfe-4b82-b847-fdcb0bd3e182.mov
https://user-images.githubusercontent.com/91458884/161518069-476abf20-61b1-45b9-8f09-a5b86b1f37b5.mp4

<img width="200" alt="before" src="https://user-images.githubusercontent.com/91458884/161518664-748779cf-0238-47b9-b23e-38b1d5e0decf.png">
<img width="200" alt="onFocus" src="https://user-images.githubusercontent.com/91458884/161518668-d87bec4d-dd65-474b-a5c8-f1d4a0aede15.png">

**Smartphone (please complete the following information):**
 - Device: Samsung a70, Samsung a71
  - OS: Android 11
 - Browser Chrome 
 - Version 99.0.4844.88

**Additional context**
This seems to be only an issues on chromium based browsers.

**Comment by severmatej** [comment]
@richnologies seems to be an issue with chrome version. On the Chrome beta version, this issue seems to be resolved. Works on older versions as well. This issue can be closed.

**Comment by richnologies** [comment]
Thanks @severmatej for the issue and finding the solution. I will notify the Stripe team in case someone else found it in the meantime.
