### ISSUE TITLE
[BUG] Payment Request Button - Do not register event listeners for both `source` or `paymentmethod`. Only one of them will succeed.

### ISSUE THREAD

**Issue by kieran-mgc** [richnologies/ngx-stripe#169]
The Payment Request Button Component is registering event listeners on all of 'token', 'source' and 'paymentmethod'. Because of this, stripe seems to try and create both a source and a payment method. This seems to have two different outcomes:

1. Confirming the card payment will fail with the error "Customer cus_xxxxxxxxxxxxxxxxxxxxxxxx does not have a linked source with ID src_xxxxxxxxxxxxxxxxxxxxxxxx"
2. An unintended request to /sources will fail with a "token_already_used" error. The payment request lightbox will appear to fail but the payment will succeed.
{
  "error": {
    "code": "token_already_used",
    "doc_url": "https://stripe.com/docs/error-codes/token-already-used",
    "message": "The token tok_xxxxxxxxxxxxxxxxxxxxxxxx has already been used. Each token can only be used once to create a source.",
    "param": "token",
    "type": "invalid_request_error"
  }
}

Additionally stripe throws a warning while creating the payment request element - "Do not register event listeners for both `source` or `paymentmethod`. Only one of them will succeed."

 - OS: macOS
 - Browser Chrome 101.0.4951.54, Safari 14.1

You can see in this gist (https://gist.github.com/maxchehab/03200297a88480c35b3d3967dd9543dd) at line 4665 how Stripe uses the presence of an event listener on "sources" to determine whether to create a source from the payment request

**Comment by dskibin** [comment]
Hi @kieran-mgc 
Seems i have same issue.

**Comment by richnologies** [comment]
Hi @kieran-mgc and @dskibin,

You're both right, we are working on it, hope to have a fix soon. 

Sorry about the inconvenience 

Kind regards,

R

**Comment by dskibin** [comment]
@richnologies thank you!

**Comment by richnologies** [comment]
Sorry, of course @kieran-mgc, let me know please if it works for you too

Thanks for patience. Busy week :(

**Comment by dskibin** [comment]
Hi Ricardo. We are using Angular 9.
Thank you very much!

**Comment by richnologies** [comment]
Done, here is the list of new versions:

- v13.2.1
- v12.8.2 `npm i ngx-stripe@v12-lts`
- v11.2.0 `npm i ngx-stripe@v11-lts`
- v10.3.0 `npm i ngx-stripe@v10-lts`
- v9.4.0 `npm i ngx-stripe@v9-lts`

**Comment by dskibin** [comment]
Thank you for your help and library in general!

**Comment by richnologies** [comment]
Hey @dskibin @kieran-mgc,

Did fix work for you?

**Comment by dskibin** [comment]
Hi @richnologies, sorry for late response.
Yes, the fix worked! 
Thank you!

**Comment by kieran-mgc** [comment]
Sorry for the late reply, I haven't had a chance to test this just yet but the commit looks sound. Thanks for working on this issue and for the great library.
