### ISSUE TITLE
Error: node_modules/ngx-stripe/lib/services/stripe.service.d.ts:2:2305 - error TS2305: Module '"@stripe/stripe-js"' has no exported member 'CollectBankAccountForSetupOptions'

### ISSUE THREAD

**Issue by rbanno** [richnologies/ngx-stripe#172]
**Describe the bug**
After upgrading to version ngx-stripe 13.2.1 & stripe-js 1.32.0 I am receiving multiple errors

Including:
Error: node_modules/ngx-stripe/lib/services/stripe.service.d.ts:2:2305 - error TS2305: Module '"@stripe/stripe-js"' has no exported member 'CollectBankAccountForSetupOptions'

**To Reproduce**
Angular at 13.3.11

I've tried multiple times but not sure whether it's a compatibility issue or whether I am doing something wrong, in terms of dependencies

**Comment by richnologies** [comment]
Hi @rbanno,

I've created an example in Stackblitz using your indications and it seems to be working for me:

https://stackblitz.com/edit/ngx-stripe-issue-172

Is not a complete example, I'm just trying to replicate your problem. Am I missing something?

Maybe you can make some changes to that example to replicate the issue so I can try to fix it. 

Thanks in advance,

R

**Comment by BojanKogoj** [comment]
Had the same issue. Problem was I updated `ngx-stripe`, but forgot to update `@stripe/stripe-js`.
