### ISSUE TITLE
[BUG] -  NGX-STRIPE initialization failed in build

### ISSUE THREAD

**Issue by GuilhermeAbreu** [richnologies/ngx-stripe#179]
**Describe the bug**

When installing the ngx-stripe package and starting my application it shows the following error.
![image](https://user-images.githubusercontent.com/50218062/190838912-22db9e64-7eba-4ea2-8cc0-249d1c3e2f6b.png)
![image](https://user-images.githubusercontent.com/50218062/190838923-2dc66297-fec4-4078-a27a-d187ba7f78c7.png)

**To Reproduce**

just install, configure the module and run the app

**Expected behavior**
That there is successful compilation

**Screenshots**
![image](https://user-images.githubusercontent.com/50218062/190838966-18218c7f-ff44-4b99-8d40-85d3b1e3955e.png)
![image](https://user-images.githubusercontent.com/50218062/190838977-cf748cd5-fa11-45cc-9454-4ecc5a36aa9f.png)
![image](https://user-images.githubusercontent.com/50218062/190838983-1c4fd14e-7061-43c2-91b0-c3a7f8e27c98.png)
![image](https://user-images.githubusercontent.com/50218062/190838998-119cb3dc-e582-4012-a44f-95609c256bde.png)

**Desktop (please complete the following information):**
 - Windows 10, 12GB RAM, 1TB SDD ,I3 Intel, 64bits
 - Browser (Chrome)
 - Version (105.0.5195.125)

**Comment by richnologies** [comment]
Hi @GuilhermeAbreu, can you please confirm me the versions you're using.

- I can see in your screenshots you're using Angular@13.2.7, is that correct?
- But I can't see which version of ngx-stripe are you trying to use, can you please share it with me to replicate

Thanks

R

**Comment by GuilhermeAbreu** [comment]
angular: 13.2.7
ngx-stripe: 14.1.0

**Comment by richnologies** [comment]
Hi @GuilhermeAbreu, I can replicate your issue. You just need install the same major version of ngx-stripe:

`npm i ngx-stripe@13`

We intentionally bump versions with Angular to match:
https://ngx-stripe.dev/docs/installation#table-versions

Thanks for letting me know. I will update peerDependencies immediately. If the problem persist after switch to v13 please let me know

**Comment by GuilhermeAbreu** [comment]
Thank you very much for your agility and speed.

With ngx-stripe in v13 the problem was solved.

follow build images.

![image](https://user-images.githubusercontent.com/50218062/191862202-14be81f2-2cd3-4f26-8d5f-1fd6934a314b.png)
![image](https://user-images.githubusercontent.com/50218062/191862195-de3129f1-d306-4b22-b1ea-d5e73d35392d.png)
