### ISSUE TITLE
Using ngx-stripe with AOT compilation

### ISSUE THREAD

**Issue by BenoitZugmeyer** [richnologies/ngx-stripe#18]
I am trying to use `ngx-stripe` in a project compiled with AOT: it seems that the key is not injected in the `StripeService` (the `key` argument is `undefined`). The exact same code compiled without the `--aot` flag is working as expected.

I am not sure how you could fix this. Maybe distribute the source .ts files in the NPM package?

**Comment by richnologies** [comment]
Hi @BenoitZugmeyer, sorry about the delay. Is this still a problem? We have this repo to test the module: https://github.com/richnologies/stripe-test, and is working so far. 

Can you provide some extra info about versions of angular and ngx-stripe you are using? If you prefer this to be private, feel free to contact me by email.
