### ISSUE TITLE
Show/Hide card element

### ISSUE THREAD

**Issue by robfarmergt** [richnologies/ngx-stripe#19]
Any recommendation for showing/hiding the card element? I'm using an *ngIf to show/hide the card entry element. If I change the variable in the *ngIf to add/remove the element and try to call `this.card.mount()` i get an error: `webpack-internal:///../../../core/esm5/core.js:1655 ERROR Error: You must provide a Stripe Element or a valid token type to create a Token.`

I'm assuming this is because the element isn't in the DOM yet.

I'm doing this to allow a user to update their card details and don't want the form fields to be shown initially.

**Comment by robfarmergt** [comment]
I was able to achieve this using the StripeCardComponent method.

**Comment by oussamaLaribi** [comment]
can u explain to me  how to Show/Hide the card element
