### ISSUE TITLE
I am trying to embed stripe pricing table inside Angular application , component not recognized

### ISSUE THREAD

**Issue by galearemus** [richnologies/ngx-stripe#191]
Would be great to add support for stripe pricing tables inside ngx Stripe as well , as Angular does not allow external scripts to be run and this feature is really a game changer

 I was considering using a workaround to run that script inside my Angular but I don't know if it will cause problems.

**Comment by galearemus** [comment]
![image](https://user-images.githubusercontent.com/37559077/206430113-9adbe7b2-1366-4897-b6ab-e2eb0c3cea2b.png)
here you can see the error I am facing

**Comment by richnologies** [comment]
Hi @galearemus,

Sorry about the delay. I'm you've figure it out by now, but I don't understand what do you mean by Angular not allow external scripts.

You can add the script to your index.html without any issues and then use the custom element they provide.

The only Angular quirk is that you have to add `CUSTOM_ELEMENTS_SCHEMA` to your modules schemas. Here is a Stackblitz example:

https://stackblitz.com/edit/ngx-stripe-pricing-table?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html

let me know if this helps

Regards,

R

**Comment by galearemus** [comment]
Great , I will try this solution this afternoon.
 I have a question. Are you planning in the near future to adapt the
products table to be linked with a customer and actually display the
current active subscription so that it can be managed within that view
(upgrade quantity, cancel) so on...

În lun., 16 ian. 2023 la 09:02, Ricardo Sánchez ***@***.***>
a scris:
