### ISSUE TITLE
Using with Reactive Forms

### ISSUE THREAD

**Issue by picosam** [richnologies/ngx-stripe#2]
Also, please, how does the `buy()` action get invoked exactly? Do you have an HTML with a `ReactiveForm` example please? Thanks again!

**Comment by picosam** [comment]
LOL, I was literally creating a pull request to update the README file when I saw your changes. Thank you :)

**Comment by richnologies** [comment]
I merge it anyway. Thanks for the contribution and sorry about my english 👍

**Comment by richnologies** [comment]
Also I add a component to simplify the mount process. Opinions and suggestions are very welcome

**Comment by picosam** [comment]
I just saw it, that's great and very helpful! I will use it right now and let you know if anything is not working as intended :)
