### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'StripeCardNumberComponent' before initialization

### ISSUE THREAD

**Issue by shahidnsu** [richnologies/ngx-stripe#200]
I am following the ngx-stripe doc. But I am getting this error.

![Screenshot 2023-02-05 at 5 59 09 PM](https://user-images.githubusercontent.com/19619396/216817389-236821ba-8c37-4b18-8a6b-1263cdfa41b8.png)

**Comment by richnologies** [comment]
Hi @shahidnsu, I'm gonna need a bit of context:

your `ngx-stripe` version
your `angular` version

a snippet of the code would be great to be able to replicate

**Comment by richnologies** [comment]
Hi @shahidnsu

I introduce an error yesterday making changes to the `ngxStripeCardGroup` directive. If you're using version `v.15.4.0` maybe that is the reason for this error. If that is the case, please update to `v15.4.1` and try again. 

If not, please, send me the details from my previous comment

Sorry for inconvenience.

**Comment by shahidnsu** [comment]
Hey you can check my code from this repo [https://github.com/shahidnsu/testing-stripe-](GitHub repo)

**Comment by shahidnsu** [comment]
> Hi @shahidnsu, I'm gonna need a bit of context:
> 
> your `ngx-stripe` version your `angular` version
> 
> a snippet of the code would be great to be able to replicate

Hey you can check my code from this repo [github repo](https://github.com/shahidnsu/testing-stripe-)

**Comment by richnologies** [comment]
Hi @shahidnsu, just update the latest version. That should fix the problem

```shell
npm i ngx-stripe@15.4.3
```

**Comment by shahidnsu** [comment]
issue solved thank you
