### ISSUE TITLE
[BUG] CSP Content Security Policy Errors

### ISSUE THREAD

**Issue by CmpHDL** [richnologies/ngx-stripe#202]
Getting CSP Errors:

Chrome:
```
[Report Only] Refused to compile or instantiate WebAssembly module because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```

Firefox: 
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). pagewrap.bundle.js
Content Security Policy: The page’s settings observed the loading of a resource at inline (“script-src”). A CSP report is being sent. pagewrap.bundle.js
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). pagewrap.bundle.js
Content Security Policy: The page’s settings observed the loading of a resource at inline (“script-src”). A CSP report is being sent. pagewrap.bundle.js
```

**Comment by richnologies** [comment]
Hey @CmpHDL,

The error message is a bit confused to me, but `ngx-stripe` does not use WebAssembly at all

However, you do need to add some URLs to your CSP to use StripeJS: 
https://stripe.com/docs/security/guide#content-security-policy

Regards,

R

**Comment by CmpHDL** [comment]
@richnologies I tried adding the ones from checkout.
```html
<meta http-equiv="Content-Security-Policy" content="connect-src https://checkout.stripe.com; frame-src https://checkout.stripe.com; script-src https://checkout.stripe.com; img-src https://*.stripe.com;">
```

However then in blocks internal angular things such as its runtime and polyfills.
```
Content Security Policy: The page’s settings blocked the loading of a resource at http://localhost:4201/runtime.js (“script-src”). 100
Content Security Policy: The page’s settings blocked the loading of a resource at http://localhost:4201/polyfills.js (“script-src”). 100
Content Security Policy: The page’s settings blocked the loading of a resource at http://localhost:4201/styles.js (“script-src”). 100
Content Security Policy: The page’s settings blocked the loading of a resource at http://localhost:4201/scripts.js (“script-src”). 100
Content Security Policy: The page’s settings blocked the loading of a resource at http://localhost:4201/vendor.js (“script-src”). 100
Content Security Policy: The page’s settings blocked the loading of a resource at http://localhost:4201/main.js (“script-src”).
```

**Comment by richnologies** [comment]
I see, please, try to add the ones from Stripe.js and let's see if that fixes your problem

**Comment by CmpHDL** [comment]
Here is the tag with both added.
```html
<meta http-equiv="Content-Security-Policy"
        content="connect-src https://api.stripe.com https://maps.googleapis.com https://checkout.stripe.com; frame-src https://js.stripe.com https://hooks.stripe.com https://checkout.stripe.com; script-src https://js.stripe.com https://maps.googleapis.com https://checkout.stripe.com; img-src https://*.stripe.com;">
```

Same issue.

**Comment by CmpHDL** [comment]
Duly note we have no current CSP policy implemented. We get these CSP errors only when important the ngx-stripe package.

**Comment by richnologies** [comment]
You're missing 'self', that is why you're getting errors related to your local assets

**Comment by CmpHDL** [comment]
Can you provide an example meta tag?

**Comment by richnologies** [comment]
<meta http-equiv="Content-Security-Policy"
        content="connect-src 'self' https://api.pluto.ricardosanchez.dev https://api.stripe.com https://checkout.stripe.com; frame-src 'self' https://js.stripe.com https://hooks.stripe.com https://checkout.stripe.com; script-src 'self' https://js.stripe.com https://maps.googleapis.com https://checkout.stripe.com; img-src 'self' https://*.stripe.com;">

**Comment by richnologies** [comment]
Sorry, just edited the comment, you can remove `https://api.pluto.ricardosanchez.dev` if have copy it, that's just my own API to make tests

**Comment by CmpHDL** [comment]
```
ERROR Error: Uncaught (in promise): EvalError: call to Function() blocked by CSP
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
```

**Comment by CmpHDL** [comment]
I fixed the Function() one but the
`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`
From [content.bundle.js]

**Comment by richnologies** [comment]
If you have inline code, you need to add 'unsafe-inline'

**Comment by richnologies** [comment]
I'd suggest you to check the CSP documentation. NgxStripe does not use inline evaluation or calling Function directly and I'm pretty sure neither does Stripe

**Comment by CmpHDL** [comment]
Thank you, I managed to avoid the unsafe-inline and tracked down most the rest, down to one but it may not be csv related (and probably isn't ngx stripe related)
main.ts:11 Refused to load the image 'data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg'
Any idea?

**Comment by richnologies** [comment]
NO problem, CSP can be a pain

Have you try add data:?

img-src 'self' data: https://*.stripe.com;

**Comment by CmpHDL** [comment]
Woo! That killed the last one in chrome! Thank you!

Getting one last one in firefox
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). [content.bundle.js]
```

This one is "solved" but using 'unsafe-inline' under script-src however do you know of a way I can track this down instead? Chrome was giving more helpful hints as to where but firefox is vague and just says "in the bundle".

**Comment by richnologies** [comment]
No idea. It can be anything. Any code that you have on an HTML page such as onclick or onload. If I'm not mistaken, even Angular Material has it for a while. They have an onload with code. That will break inline for CSP

**Comment by CmpHDL** [comment]
Thank you, I think I found out which package is doing it going to remove it and see if anything changes. Thank you so much for your help!

**Comment by richnologies** [comment]
No problem, good luck

**Comment by CmpHDL** [comment]
@richnologies I lied, I had accidentally tracked down the source of the other warnings and had it commented out so all had seemed well.

Its coming from when using `StripeService`, the warnings are not present if `NgxStripeModule.forRoot()` is loaded but once `StripeService` is dependency injected, the errors appear.

**Comment by CmpHDL** [comment]
All look like 
```Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
```

**Comment by CmpHDL** [comment]
I even tried adding `'unsafe-eval'` and `'unsafe-inline'` to `script-src` and get the same errors.

**Comment by richnologies** [comment]
We use this library in production with CSP with no problems, so at this point I can't replicate. 

So, if you want me to help, I'd suggest that you create a minimal Angular CLI project that produces this error and send it to me to: support@ngx-stripe.dev

I'll have a look and try to troubleshoot the problem

**Comment by CmpHDL** [comment]
I figured it out since I was trying to debug that last error from last time and found the origin, looks like its related to this issue. Something that Redux Devtools is doing (both on chrome and firefox) is triggering this. If I remove the redux devtools plugin, all goes away.

**Comment by CmpHDL** [comment]
https://github.com/reduxjs/redux-devtools/issues/380
Found the same exact issue on their github :)

Which apparently is a firefox bug
https://bugzilla.mozilla.org/show_bug.cgi?id=965637

Happy others have this same exact issue and its documented.
Unhappy with this as there has been no solution since 2017 (5 years)

**Comment by richnologies** [comment]
Wow!! Thanks for sharing, very interesting and now we have this issue in case someone else has this issue. 

Now that you mention I had issues in the past with Redux Devtools. I haven't use it in a while. 

Sorry about the inconvenience, but nice work troubleshooting this.

**Comment by CmpHDL** [comment]
Yep, decade old esoteric Firefox bug, I miss the days when errors were our fault. Thanks for your help @richnologies
