### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by angiexroap** [richnologies/ngx-stripe#206]
**Describe the bug**
Hi sir, the class called StripeElementsOptions was changed with the last update of package stripe-js, the module ngx stripe  present an error with that, now is called BaseStripeElementsOptions, check it please.

**To Reproduce**
1. run application angular
2. see error'

**Expected behavior**
run the app

**Screenshots**

![image](https://user-images.githubusercontent.com/121903576/227029283-147b25d8-fd44-4ec4-9401-61a313ca9959.png)

"@angular/compiler": "^15.1.0",
"@angular/core": "^15.1.0",
"ngx-stripe": "^15.5.1",
"@stripe/stripe-js": "^1.50.0",

**Comment by richnologies** [comment]
Hey @angiexroap, can you please try to update to. `@stripe/stripe-js@1.51.0` and let me know if that works for you?
