### ISSUE TITLE
[BUG] comfirmSetup doesnt resolve

### ISSUE THREAD

**Issue by christ0089** [richnologies/ngx-stripe#209]
**Describe the bug**
When the SetupIntent of the payment elements is confirmed via de confirmSetup the subscription does not emit any value to the subscription 

**To Reproduce**

    "@angular/animations": "^15.2.8",
    "@angular/common": "^15.0.0",
    "@angular/core": "^15.0.0",
    "@angular/fire": "^7.5.0",
    "@angular/forms": "^15.0.0",
    "@angular/platform-browser": "^15.0.0",
    "@angular/platform-browser-dynamic": "^15.0.0",
    "@angular/platform-server": "^15.0.0",
    "@angular/router": "^15.0.0",    
    "@nguniversal/express-engine": "^15.2.1",
    "@stripe/stripe-js": "1.52.0",
    "ngx-stripe": "^15.6.0",
   
    Using Angular Universal

**Expected behavior**
SetupIntent Should emit a value whether its an error or a success but none are applying

**Screenshots**
Method to confirm Setup Intent followed from example in website
<img width="568" alt="Screen Shot 2023-05-12 at 11 07 55" src="https://github.com/richnologies/ngx-stripe/assets/7467283/0a46779f-12cd-4974-ad13-63ec27ca7097">

Payment Element in Question 
<img width="496" alt="Screen Shot 2023-05-12 at 11 08 27" src="https://github.com/richnologies/ngx-stripe/assets/7467283/c92f415f-78ba-4244-bdbe-3ad4f15cbba2">
<img width="954" alt="Screen Shot 2023-05-12 at 11 08 36" src="https://github.com/richnologies/ngx-stripe/assets/7467283/f9c18d84-05fb-496d-b1a0-d5c0ab854a1b">

Previously there was an event emmited 
<img width="305" alt="205388827-f63d9673-79db-4ed8-a47f-d435b13d5402" src="https://github.com/richnologies/ngx-stripe/assets/7467283/39c36964-a813-4030-a517-4eba0fcaa28e">

Now this is the only event that logs in the network
<img width="219" alt="Screen Shot 2023-05-12 at 11 26 44" src="https://github.com/richnologies/ngx-stripe/assets/7467283/fb19f1bf-ac61-4022-8ea2-605598052928">

**Desktop (please complete the following information):**
 - OS: Mac Ventura
 - Browser Chrome

**Additional context**

**Comment by richnologies** [comment]
Hey @christ0089,

Sorry for the delay, but new versions have been release:

- 16.1.1
- 15.7.1
- 14.5.0

They should fix this issue for you

Regards

R
