### ISSUE TITLE
postal code is missing in ngx-stripe-payment [BUG]

### ISSUE THREAD

**Issue by ahammadfaishal** [richnologies/ngx-stripe#210]
**Describe the bug**
Postal code is missing in ngx-stripe-payment component, and I didn't find any configuration to add it manually. 

**To Reproduce**
I tried 
` <ng-container *ngIf="elementsOptions?.clientSecret">
        <ngx-stripe-payment
          [appearance]="appearance"
          [clientSecret]="elementsOptions?.clientSecret"
        ></ngx-stripe-payment>
      </ng-container>
`

and 
`public elementsOptions: StripeElementsOptions = {
    locale: 'en',
     clientSecret: '****secret_key****',
    currency: 'aud',
    capture_method: 'automatic'
  };`
`@ViewChild(StripePaymentElementComponent) paymentElement: StripePaymentElementComponent;
  appearance: Appearance = {
    theme: 'stripe',
    variables: {
      colorPrimary: '#673ab7',
    }
    },
  };
  stripeTest: FormGroup;`
  
`"@angular/common": "^12.0.5",`
`"@stripe/stripe-js": "^1.53.0",`
`"ngx-stripe": "v12",`

**Expected behavior**
![image](https://github.com/richnologies/ngx-stripe/assets/30669559/ffe81db7-3309-4eaa-ac69-b227d292dfc7)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 113.0.5672.93 (Official Build) (64-bit)

**Comment by richnologies** [comment]
Hi @ahammadfaishal,

This repo only maintains the Angular wrapper for StripeJS. We don't handle that functionality. Stripe does it. It automatically decides whether or not to show the post code and the format it should have depending on the country. If you see the Stripe Docs you will notice the same happens for Australia:

<img width="1506" alt="image" src="https://github.com/richnologies/ngx-stripe/assets/4794630/10399680-a57f-401f-a05a-d82da24f0ed4">

There is an option to do the exact opposite and never ask for it. This way you can add a field to collect the postcode. In that case you'll have to pass the value of that field when you try to confirm the payment. https://stripe.com/docs/js/elements_object/create_payment_element

You can also raise this issue in the main StripeJS repo: https://github.com/stripe/stripe-js

Sorry I don't have a better answer. 

Let me know if there is anything else I can help you with

Regards,

R
