### ISSUE TITLE
[BUG] confirmPayment method returns "elements should have a mounted Payment Element or Express Checkout Element" error

### ISSUE THREAD

**Issue by nataliao2613** [richnologies/ngx-stripe#211]
**Describe the bug**
I'm creating an payment module application, which is split into few steps. When user selects credit card as payment method, next step is filling stripe payment element form, next one is custom form for billing information, when both steps are completed, stripe confirmPayment method is run and every time "Invalid value for stripe.confirmPayment(): elements should have a mounted Payment Element or Express Checkout Element." error message appears.

**Expected behavior**
confirmPayment is completed and return result.

**Screenshots**
![Screenshot 2023-05-23 at 16 51 31](https://github.com/richnologies/ngx-stripe/assets/49456447/d57770cf-d378-4eac-8a35-697af1962b27)

**Comment by richnologies** [comment]
Hey @nataliao2613, sorry I miss this one.

I'm having issues understanding the problem. Maybe you can provide me a small snippet on what are you trying to do. 

Can you also try to the new version: `15.7.1` in case that help?

Appreciate any feedback

Regards

R
