### ISSUE TITLE
[Feature Request] Support for dynamic BNPL Payment Method Messaging

### ISSUE THREAD

**Issue by lcottingham** [richnologies/ngx-stripe#214]
**Is your feature request related to a problem? Please describe.**
As buy now pay later methods are gaining in popularity, it's very useful to be able to offer clear messaging. Laws and guidelines are very strict around finance products, so the messaging must be in-line with these guidelines. Luckily, they all offer dynamic messaging that will ensure we're always within the guideline - https://stripe.com/docs/payments/payment-method-messaging

**Describe the solution you'd like**
Creating a new component that can take an options object to control the payment types, amount, as well as utilising the Appearance API for the 'element'

**Describe alternatives you've considered**
I've looked at using the stripe factory to create a new element that can be 'mounted'.

**Additional context**
https://stripe.com/docs/payments/payment-method-messaging

**Comment by richnologies** [comment]
Hey @lcottingham, thanks for you this request. I have no idea about this element. I will add it as soon as possible following their guidelines. When I have the PR, would you be interesting in having a look?

**Comment by lcottingham** [comment]
> Hey @lcottingham, thanks for this request. I have no idea about this element. I will add it as soon as possible following their guidelines. When I have the PR, would you be interesting in having a look?

Happy to give it a test and review it for you once there is a PR 👍

**Comment by richnologies** [comment]
Hey @lcottingham, new version have been release:

- 16.1.1
- 15.7.1
- 14.5.0

That should work with the new component. Docs are not completed yet, but you can check this trivial example:
https://github.com/richnologies/ngx-stripe/blob/main/projects/ngx-stripe-docs/src/app/examples/payment-method-messaging.component.ts

If you're using an older Angular version I'll be adding support for v12 and v13 over the weekend

Let me know if this works for you

Regards,

R

**Comment by lcottingham** [comment]
Oh, fantastic! Brilliant work - I'll give this a test now. Working on Angular `16.0.4`
