### ISSUE TITLE
Chrome Extension : Integration impossible without HTTPS.

### ISSUE THREAD

**Issue by STK913** [richnologies/ngx-stripe#22]
Hello,

I developed a browser WebExtension with ngx-stripe, but it's impossible to make a payment without being in HTTPS. This error message appears:
ERROR Error: Live Stripe.js integrations must use HTTPS. For more information: https://stripe.com/docs/stripe-js/elements/quickstart#http-requirements
It works well with the test key, but not with the production key.

Do you have a solution to work around this problem?

Thank you for your answer.

Regards.

**Comment by richnologies** [comment]
Hi @STK913, I am afraid that as far as I know is not possible. In any case, this is a limitation of Stripe, not the module. I suggest you try to ask in Stackoverflow

**Comment by STK913** [comment]
Hello,
Yes, unfortunately :s Stripe's support also confirmed that it was not possible.
My workaround: host an HTML page with Stripe on a remote server with HTTPS, then integrate it into the application with an iframe and communicate between the server and the page with postMessage.
