### ISSUE TITLE
[BUG] Module '"ngx-stripe"' has no exported member 'provideNgxStripe'.

### ISSUE THREAD

**Issue by german-e-mas** [richnologies/ngx-stripe#220]
I'm trying to setup `ngx-stripe` using `bootstrapApplication` but I cannot use the `provideNgxStripe` method, as it is not exported.

I'm using `node v18.16.0` and `npm i ngx-stripe` installed `16.1.2`.

The installed version does not include an export of `provideNgxStripe`.

---

The [docs](https://ngx-stripe.dev/docs/setup-application) mention the provide function, and I see it exported correctly in the [public api](https://github.com/richnologies/ngx-stripe/blob/main/projects/ngx-stripe/src/public_api.ts) of the `main` branch.

Has this not yet been released? If so, when do you think it's going to be released?

In the meantime, how can I use the existing `NgxStripeModule` alongside `bootstrapApplication`?

**Comment by german-e-mas** [comment]
Just in case, using `importProvidersFrom(NgxStripeModule.forRoot(STRIPE_PUBLIC_KEY))` seems to do the trick.

**Comment by richnologies** [comment]
Hey @german-e-mas, sorry, my fault, I've been very busy this last couple of weeks. 

I now version has been release `16.2.0` that should include the method. 

Please let me know if that works for you
