### ISSUE TITLE
i used this but in my case still not working in iphone 8 browser label is showing but input not showing please help

### ISSUE THREAD

**Issue by sherz12r** [richnologies/ngx-stripe#222]
i used this but in my case still not working in iphone 8 browser label is showing but input not showing please help
![WhatsApp Image 2023-08-31 at 23 00 22](https://github.com/richnologies/ngx-stripe/assets/46225971/d9f3b62a-b23a-4e06-a6ea-ada92426f0da)

_Originally posted by @sherz12r in https://github.com/richnologies/ngx-stripe/issues/129#issuecomment-1701600583_

**Comment by richnologies** [comment]
Hey @sherz12r, 

NgxStripe does not render the components directly. We delegate that job on the StripeJS library. It seems to me this issue has to be on their side. I would recommend you open an issue there. 

Also, I'm afraid I have no way to replicate on an iPhone 8

If you do open that PR please add a reference here in case it might help other users

Thanks
