### ISSUE TITLE
Request for Beta Feature to block certain card types

### ISSUE THREAD

**Issue by nknoeppel** [richnologies/ngx-stripe#230]
Hello,

My company is working on an integration using this package. Our business has the need to disable Amex cards due to their higher fees. Our Stripe implementation team has pointed me to the following documentation: https://stripe.com/docs/payments/customize-payment-element#filter-card-brands. 

It appears I am unable to accomplish this using ngx-stripe, based on the examples/documentation I've seen. Any way we can get this beta feature implemented? Or, if not, could you potentially advise on if this is possible using the existing latest version?

Thanks!

**Comment by richnologies** [comment]
Hey @nknoeppel, I do not have access to that beta yet, meaning in that link I can't see anything.

I'm more than happy to add support for the implementation.

Let's respect the beta visibility. Can you send me a direct message (ric.sanchez@me.com) with some docs on how would you do it with StripeJS so I can try to adapt it to ngx-stripe?

**Comment by richnologies** [comment]
I'm closing this now due to inactivity

**Comment by nknoeppel** [comment]
I sent you an email with the details you were asking for. Did you not receive it?
