### ISSUE TITLE
[BUG] Payment Request Button throws error in console

### ISSUE THREAD

**Issue by yuriityrpych0611** [richnologies/ngx-stripe#231]
Hello, 

I have issues with ngx stripe request button that it asks about using paymentRequest.canMakePayment() before mounting the Element. And the same error comes in console on your official website where you show example of using <ngx-stripe-request-button>

<img width="1135" alt="image" src="https://github.com/richnologies/ngx-stripe/assets/149520707/2d6339b3-294a-4fda-80c0-d8e5ad8b5050">

**Comment by richnologies** [comment]
Hey @yuriityrpych0611, can you provide a small snippet of code on what are you doing. That would help me to replicate faster. Also, please indicate what version of Angular and ngx-stripe you're using

Thanks in advance

**Comment by yuriityrpych0611** [comment]
Hey, I am using 

 "@angular/common": "~15.2.0",
"@stripe/stripe-js": "1.54.1",
 "ngx-stripe": "^15.7.1".


In order to replicate that issue enough just to launch that code snippet from [here](https://ngx-stripe.dev/docs/payment-request-button). 

Just to add 
`<ngx-stripe-payment-request-button
  [paymentOptions]="paymentRequestOptions"
  (paymentMethod)="onPaymentMethod($event)"
  (shippingaddresschange)="onShippingAddressChange($event)"
  (notavailable)="onNotAvailable()"
></ngx-stripe-payment-request-button>`

tag

**Comment by richnologies** [comment]
Hey @yuriityrpych0611, thanks for reporting this issue. I've release a new version `15.7.2` that should address that problem. Please let me know if that works for you, so I can publish the other Angular versions too

Thanks

**Comment by yuriityrpych0611** [comment]
Hey, yes it resolved that error. Thank you
