### ISSUE TITLE
Angular 17

### ISSUE THREAD

**Issue by michaelkrog** [richnologies/ngx-stripe#232]
**Is your feature request related to a problem? Please describe.**
Cannot upgrade to ng17 without overriding devs for nix-stripe.

**Describe the solution you'd like**
More flexible dependency versions in ngx-stripe.

**Describe alternatives you've considered**
Create new release for ng17.

**Comment by richnologies** [comment]
Hey @michaelkrog, working on it right now

**Comment by richnologies** [comment]
New Version `17.0.0` has been released

Please let me know if you have any issues upgrading
