### ISSUE TITLE
Possibility to see CB images

### ISSUE THREAD

**Issue by rudyhadoux** [richnologies/ngx-stripe#233]
Hi,

With Stripe Elements for a payment (and Angular 17), is it possible to display the bank cards pictures in the numbers input ?

**Comment by richnologies** [comment]
Hey @rudyhadoux, can you be more specific, are you talking about the payment element? or the any of the other Bank Elements?

**Comment by rudyhadoux** [comment]
Hi.
Those bank cards pictures.
<img width="467" alt="Capture d’écran 2023-11-16 à 18 00 19" src="https://github.com/richnologies/ngx-stripe/assets/45458482/7d34c890-9db2-4b59-b565-5650fe29339c">

**Comment by richnologies** [comment]
Yeah, Stripe itself takes care of that. Ngx Stripe is just a wrapper around it. Should work fine

**Comment by rudyhadoux** [comment]
It is an example.
https://stripe.d4h859zm8fz5n.amplifyapp.com 
With ngx-stripe and @stripe/stripe-js.
No pictures...

**Comment by richnologies** [comment]
May I have the link to the example where they did work?

**Comment by rudyhadoux** [comment]
Sorry, what do you mean ?

**Comment by richnologies** [comment]
The first example where the logs where actually displayed, is that an Stripe example?

**Comment by rudyhadoux** [comment]
It is my own example with ngx-stripe and @stripe/stripe-js.

**Comment by richnologies** [comment]
> Hi. Those bank cards pictures. <img alt="Capture d’écran 2023-11-16 à 18 00 19" width="467" src="https://user-images.githubusercontent.com/45458482/283535129-7d34c890-9db2-4b59-b565-5650fe29339c.png">

So, this example is with ngx-stripe too??

**Comment by rudyhadoux** [comment]
It is a web site with Stripe Elements.
I wait for a reply from Stripe Support.
I do not understand why Stripe does not develop an embedded solution for Angular.

**Comment by richnologies** [comment]
Great! I would appreciate if you could share what they tell you, so other can benefit

**Comment by rudyhadoux** [comment]
I found myself. I just integrated html client in Angular from : 
https://github.com/stripe-samples/accept-a-payment/tree/main/payment-element/client

**Comment by richnologies** [comment]
Oh! but that is the Payment Element, not the Card Element, right?

**Comment by richnologies** [comment]
Sorry about that, we have support for that too: https://stackblitz.com/edit/ngx-stripe-live?file=src%2Fmain.ts

Anyway, happy you find your way

**Comment by rudyhadoux** [comment]
<form id="payment-form"> is the form to pay.
That give
<img width="1863" alt="Capture d’écran 2023-11-17 à 15 28 27" src="https://github.com/richnologies/ngx-stripe/assets/45458482/74ba7cef-f702-4c29-803a-f7b4f9f6aa79">
s me that.
