### ISSUE TITLE
Stripe not blocking the fradulent cards

### ISSUE THREAD

**Issue by abhinavakhil** [richnologies/ngx-stripe#235]
Hello everyone, 

I'm currently working on an application that utilizes Stripe for processing payments. 

While we employ Stripe's fraud protection measures, we recently faced an influx of approximately 10,000 payments per day, each amounting to just 1 euro. 

I'm seeking advice on how to address this issue. How can we ensure that payments are not hindered while still effectively safeguarding against spammers? Your insights and suggestions would be greatly appreciated.

**Comment by richnologies** [comment]
Hey @abhinavakhil, I'm sorry, but I'm not the right question to ask this kind of questions. I've never have such a scale product under my supervision.

I assume you already try with Support and the Discord Server, so, I'm afraid I can't help you
