### ISSUE TITLE
[BUG] I get issue in console log: "Refused to execute inline script" when loading some ngx elemens

### ISSUE THREAD

**Issue by yuriityrpych0611** [richnologies/ngx-stripe#238]
When I just load some ngx elements like for example
<ngx-stripe-card-number>

I get these errors
<img width="1499" alt="Screenshot 2023-12-23 at 23 26 38" src="https://github.com/richnologies/ngx-stripe/assets/149520707/fb3f7489-7edb-4bc8-a62c-d42b41ab8efa">

And the same I can see on your official website
<img width="1512" alt="Screenshot 2023-12-23 at 23 27 21" src="https://github.com/richnologies/ngx-stripe/assets/149520707/cef1b665-c743-4307-9a24-ec40a4c47f2e">

**Comment by richnologies** [comment]
Hey @yuriityrpych0611, please check the following link: https://stripe.com/docs/security/guide#content-security-policy

I think you might need to update your Content Security Policy
