### ISSUE TITLE
Make ngs-stripe compatible with stripe/stripe-js v3.0.0

### ISSUE THREAD

**Issue by woutersteven** [richnologies/ngx-stripe#242]
**Is your feature request related to a problem? Please describe.**
Dependency issue, warnings during npm install

**Describe the solution you'd like**
Support for stripe/stripe-js v3.0.0

```bash
npm WARN Found: @stripe/stripe-js@2.4.0
npm WARN node_modules/@stripe/stripe-js
npm WARN   @stripe/stripe-js@"^3.0.0" from the root project
npm WARN   1 more (ngx-stripe)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @stripe/stripe-js@">=2.1.7 <3.0.0" from ngx-stripe@17.0.1
npm WARN node_modules/ngx-stripe
```

**Comment by richnologies** [comment]
Hey @novelapproaches, thanks for letting me know.

I new version of the library `17.1.0` has been published to npm that should support StripeJS V3

Please, let me know if that works for you
