### ISSUE TITLE
[BUG] Unable to display name, phone & email is payment form using the billingDetails in defaultValues

### ISSUE THREAD

**Issue by ahmadallw** [richnologies/ngx-stripe#243]
**Describe the bug**
We are trying to display name, phone & email is the payment form (pre filled data) - where the options object is set to
```typescript
options: any = {
        defaultValues: {
            billingDetails: {
                name: 'Name',
                email: 'name@name.com',
                phone: '000000000',
                address: {
                    country: 'DE',
                },
            },
        },
        fields: {
            billingDetails: {
                address: {
                    country: 'auto',
                },
                name: 'auto',
                email: 'auto',
                phone: 'auto',
            },
        },
    }
``` 

the available options for billingDetails in fields object are 'auto' | 'never' when setting fields to auto fields still not showing in the payment form 

When setting fields to auto they should show on the payment form or maybe it should add new option as 'always'

![image](https://github.com/richnologies/ngx-stripe/assets/120717866/af3733e7-2fa4-493e-af49-91cc95a5039e)

we are using the following version for
"ngx-stripe": "^17.0.1",
"@stripe/stripe-js": "^3.0.0",

check the following docs https://stripe.com/docs/payments/link/add-link-elements-integration?link-integration-type=before-payment&client=html#web-collect-payment-details

**Comment by richnologies** [comment]
Hey @ahmadallw, after checking this, I believe the problem is in the payment method. This is what the docs says:

> Specify customer's billing details, which lets you pre-fill a **customer’s name, email, phone number and address if required by payment method**. Pre-filling as much information as possible streamlines the checkout process.

Notice how it says, if required by payment method. I assume that is not the case for card payment. Feel free to raise this with Stripe support. If it works with StripeJS should with ngx-stripe
