### ISSUE TITLE
[QUESTION] Documentation link

### ISSUE THREAD

**Issue by ibonetti** [richnologies/ngx-stripe#250]
Quick question, is the documentation link still https://ngx-stripe.dev/docs? I'm unable to access it.

**Comment by richnologies** [comment]
Is this still the case? It works fine for me. Can I get a screenshoot?

**Comment by ibonetti** [comment]
Maybe it's something on my end. I'll try using a vpn when i get a chance.

![image](https://github.com/richnologies/ngx-stripe/assets/37149633/9f13e303-8381-45a8-8d65-95217407b67d)

**Comment by ibonetti** [comment]
Yes, it's working though a VPN, so probably something wrong with my internet provider. 
Thanks for the reply.
