### ISSUE TITLE
[BUG] Remove Stripe Cart Element types

### ISSUE THREAD

**Issue by KeithGillette** [richnologies/ngx-stripe#252]
**Describe the bug**

While `ngx-stripe` `package.json` indicates compatibility with `@stripe/stripe-js: ^3.0.0`, updating to `@stripe/stripe-js@3.3.0` generates error `node_modules/ngx-stripe/lib/directives/elements.directive.d.ts(2,217): error TS2724: '"@stripe/stripe-js"' has no exported member named 'StripeCartElement' on `tsc`.

**To Reproduce**

- Update dependent project to `@stripe/stripe-js@3.3.0`
- Build dependent project

**Expected behavior**

No error should occur, since `ngx-stripe` claims compatibility with `@stripe/stripe-js: ^3.3.0`

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS: MacOS 14.4.1
 - Browser: N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

None

**Comment by richnologies** [comment]
Hey @KeithGillette,

Thanks for letting us know. We have release a new version `17.2.0` that should fix the problem

**Comment by KeithGillette** [comment]
Works for me. Thanks for the super-fast fix!
