### ISSUE TITLE
Angular 19 support

### ISSUE THREAD

**Issue by ghislaindemael** [richnologies/ngx-stripe#264]
Following the release of Angular 19, support would be appreciated. 

I might not be the only one whose builds must be forced due to the dependency requirements

**Comment by loneObserver1** [comment]
+1 please

**Comment by servefast-cto** [comment]
+1

**Comment by richnologies** [comment]
Hi @ghislaindemael, @loneObserver1, @woutersteven, @servefast-cto,

Thanks for your request! We're excited to let you know that version `19.0.0` of the library is now available, with full support for Angular 19 and Stripe V5.

Please be aware of the following breaking changes in this release:

- `StripeCustomCheckout` has been renamed to `StripeCheckout`.
- `StripeCustomCheckoutOptions` has been renamed to `StripeCheckoutOptions`.
- The method `initCustomCheckout` is now `initCheckout`.

Please, let us know if you found any issues with the new version
