### ISSUE TITLE
Cannot read property 'getCard' of undefined

### ISSUE THREAD

**Issue by justvamp** [richnologies/ngx-stripe#32]
Angular 5.

If I try to use Stripe form in a modal window (using NgbModal service of ng-bootstrap) there's an error "Cannot read property 'getCard' of undefined".
Seems like ```this.card``` is initialized somewhere else because html code of the window is moving
somewhere in the end of the body.

Is there any workaround for this issue?

**Comment by justvamp** [comment]
@camilocano146 Well, it's not a proper solution but quite a dirty workaround.

I just copy-pasted the modal html and worked with it myself, so that it wasn't moved somewhere. Like this:
```html
<!-- we cannot use modal window properly because otherwise this.card initializes in some wrong place -->
<div *ngIf="modalOpened" class="modal-backdrop fade show"></div>
<div *ngIf="modalOpened" role="dialog" tabindex="-1" class="modal fade show d-block">
  <div role="document" class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Add card</h4>
        <button type="button" class="close" aria-label="Close" (click)="modalOpened = false">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ngx-stripe-card class="stripe-card-style" [options]="cardOptions" [elementsOptions]="elementsOptions"></ngx-stripe-card>
        <div class="modal-footer">
          <general-button style="float: right;" type="submit" title="Add card"></general-button>
        </div>
    </div>
  </div>
```

It's not very elegant but it works. Hope it helps :)

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. Please give it a try. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week.
