### ISSUE TITLE
rxjs6 version Invalid value for create(): paymentRequest

### ISSUE THREAD

**Issue by dottodot** [richnologies/ngx-stripe#33]
Just given the rxjs6 version a try but the paymentRequestButton doesn't seem to work now

```
    this.paymentRequest = this.stripeService.paymentRequest({

    });

    this.prButton = this.elements.create('paymentRequestButton', {
      paymentRequest: this.paymentRequest
    });
```

gives an error of 

```
Uncaught Error: Invalid value for create(): paymentRequest should be a stripe.paymentRequest(...) instance. You specified: [object Object].
```

**Comment by SamuelMarks** [comment]
Maybe:

    this.prButton = this.elements.create('paymentRequestButton', {
      paymentRequest: this.paymentRequest.bind(this)
    });

**Comment by dottodot** [comment]
bind give an error of 
```
this.paymentRequest.bind is not a function
```
and the self approach just give the same result as originally posted and as I'm already attached it to a component property it's pretty must the same thing.

**Comment by dottodot** [comment]
Also the current version used with rxjs-compat only has an issue, doesn't throw any errors but doesn't show a button either.

**Comment by SamuelMarks** [comment]
Hmm, not sure then.

PS: You could always try the branch on my fork: https://github.com/SamuelMarks/ngx-stripe/tree/ng6

**Comment by dottodot** [comment]
OK took a while and after copying the code I was able to work out how to make it work.

Previously I was able to do the following

```
this.paymentRequest = this.stripeService.paymentRequest({});
this.prButton = this.elements.create('paymentRequestButton', {
     paymentRequest: this.paymentRequest
});
```

but now you need to subscribe to `this.stripeService.paymentRequest` and the pass in the the response i.e

```
this.stripeService.paymentRequest({}).subscribe(paymentRequest => {
 this.paymentRequest = paymentRequest;
 this.prButton = this.elements.create('paymentRequestButton', {
     paymentRequest: this.paymentRequest
 });
})
```

**Comment by SamuelMarks** [comment]
Looks at the Network, everyone is making their own Angular 6 compatible forks: https://github.com/richnologies/ngx-stripe/network

**Comment by dottodot** [comment]
This branch works fine just need the docs updating for `paymentRequest` as it works slightly different to the previous version as per my comment above

**Comment by richnologies** [comment]
Thanks, I will update the docs
