### ISSUE TITLE
Is not working with "NgbModal" popup

### ISSUE THREAD

**Issue by binishprabhakar** [richnologies/ngx-stripe#36]
Hi,

I want to use the strip add card functionality in popup. It is working in normal html templates. But it showing following error while using in popup. I am using Angular 5.

> ERROR Error: The selector you specified (.card-element-box) applies to no DOM elements that are currently on the page.
> Make sure the element exists on the page before calling mount().

I understand that the specified html element is not available while calling stripe service since it is dynamically added by popup. Please help me to resolve the issue

Thanks

**Comment by noahjerreel** [comment]
Hello @binishprabhakar ,

Make sure that the form or parent of the dom elements is not controlled by structural directives (like ngIf). Using structural directives, it creates or destroys the elements thus stripe can't find the element upon request.

**Comment by binishprabhakar** [comment]
Thanks
