### ISSUE TITLE
How to change input placeholder Text?  

### ISSUE THREAD

**Issue by Haribabujanjala** [richnologies/ngx-stripe#37]
Please Some one Help me out.

**Comment by kapsrocks** [comment]
How to change input placeholder Text? 
I want to change CVC to CVV

**Comment by richnologies** [comment]
Hi @adamshakhabov, I'm re-opening the use until it works for you :)

Every card component (list below) has an options input. You can pass a custom placeholder using that input. 

- ngx-stripe-card
- ngx-stripe-card-number
- ngx-stripe-card-expiry
- ngx-stripe-card-cvc

I've created a StackBlitz example for you: 
https://stackblitz.com/edit/ngx-stripe-issue-37?file=src%2Fapp%2Fapp.component.ts

as you can see there we pass an options object: 

```html
<div ngxStripeCardGroup [elementsOptions]="elementsOptions">
      <ngx-stripe-card-number [options]="cardOptions"></ngx-stripe-card-number>
      <ngx-stripe-card-expiry [options]="cardOptions"></ngx-stripe-card-expiry>  
      <ngx-stripe-card-cvc [options]="cvvOptions"></ngx-stripe-card-cvc> 
      <button (click)="createToken()">CREATE TOKEN</button>
</div>
```

In this case, card-cvc has the specific placeholder option:

```typescript
cvvOptions: StripeCardCvcElementOptions = {
    ...this.cardOptions,
    placeholder: 'CVV',
};
```

Please let me know if that answer was helpful so I can add it to the FAQs sections of the docs :)

Thanks for helping us make the library better by letting us know it was difficult to do.

Kind regards

R
