### ISSUE TITLE
Angular 7 Support

### ISSUE THREAD

**Issue by andervander** [richnologies/ngx-stripe#45]
Please update library to support angular v7

`warning " > ngx-stripe@6.0.0-rc.0" has incorrect peer dependency "@angular/common@^6.0.0-rc.1".
warning " > ngx-stripe@6.0.0-rc.0" has incorrect peer dependency "@angular/core@^6.0.0-rc.1".`

**Comment by iCodr8** [comment]
Using `npm i rxjs-compat` is not a good idea, because the goal of angular 7 is to remove this package.

**Comment by iCodr8** [comment]
https://github.com/richnologies/ngx-stripe/issues/51

**Comment by electric-ladyland** [comment]
> Using `npm i rxjs-compat` is not a good idea, because the goal of angular 7 is to remove this package.

Hence the "for now".

**Comment by electric-ladyland** [comment]
I have a fork upgrading all packages including Angular 7 [here](https://github.com/electric-ladyland/ngx-stripe). This should have most of the heavy lifting done.

I can get it to build with minimal (non-critical) tslint warnings. But I cannot get the tests to run (could not prior to upgrade) so I'm going to manually test now. Also, I am not familiar with the rollup (I guess npm packaging?) stage. So while I got it to "work", I do not know what the implications of the upgrade are on the validity of packaging.

Ultimately it seems the author needs to verify the upgrade. But it appears he has abandoned the project (?) So if anyone has advice for next steps (as far as npm goes) I'd be happy to follow up.

**Comment by electric-ladyland** [comment]
Yeah so I'm done with this library. Irresponsible to start a library like this, get 3,000+ weekly downloads, and abandon it. 

I pulled the source into my own project and aggressively refactored. Ended up with something much simpler, only 3 files, and now I have control over it.

**Comment by astr0sl0th** [comment]
@electric-ladyland Care to share?
