### ISSUE TITLE
Feature Request: Allow Locale Setting

### ISSUE THREAD

**Issue by picosam** [richnologies/ngx-stripe#5]
I can see `ElementsOptions` that has a locale property, but I'm not sure how we can set this. Also, would it be possible to accept this dynamically (as an `Observable`?) so that users of `ngx-translate` may update the locale on-the-fly when user changes language?

**Comment by richnologies** [comment]
I will add tonight the options parameter both to the elements function and to the StripeCardComponent. I sorry I miss that.

**Comment by picosam** [comment]
Hello! Any news about this?

**Comment by richnologies** [comment]
Hi, sorry for the delay. You can check the readme for the updates. Basically you can pass an options object with the locale to the elements function on the StripeService and also as a second input to the stripe component.

**Comment by picosam** [comment]
Hey! No worries, thank you. I'll try that out next week. I've seen the README though, it looks pretty clear :-)

**Comment by richnologies** [comment]
I close this due to inactivity. If the problem persists please open a new one
