### ISSUE TITLE
uBlock Origin blocking Stripe element input

### ISSUE THREAD

**Issue by electric-ladyland** [richnologies/ngx-stripe#53]
Anyone else noticed this? I know it's caused by [uBlock origin](https://github.com/gorhill/uBlock) so the problem is caused "there". And not necessarily related to this ngx implemention. But how are others dealing with this? **This adblocker has 10 million+ users**. So it's a serious issue and I can't find any info about it online. Is Stripe Elements doing something questionable that leads it to be blocked?
![image](https://user-images.githubusercontent.com/32247136/51291124-7e102e80-19dc-11e9-9096-48c345f52645.png)

**Comment by sambokai** [comment]
Related: 
stripe/react-stripe-elements#222
https://github.com/stripe/stripe-php/issues/528

**Comment by electric-ladyland** [comment]
Interesting links, but I'm not able to see what the conclusion was. Problem with adblocking extensions? Problem with Stripe? Problem with Elements?

I honestly can't believe this isn't a hotter issue... That would make me guess it's some rare version combination of any of the above that have the issue.

In any case, any advice?

**Comment by sambokai** [comment]
> Interesting links, but I'm not able to see what the conclusion was.
Me neither. I just wanted to link the issues, in an effort to increase visibility and decrease divergence.

> I honestly can't believe this isn't a hotter issue...
I agree

> That would make me guess it's some rare version combination of any of the above that have the issue.
It would be helpful to hear from more people with similar setups.

**Comment by sambokai** [comment]
It seems like these guys (https://github.com/stripe/react-stripe-elements/issues/222) contacted the AdBlock team, which in turn removed the block. 

We should do the same for uBlock Origin and Ghostery (https://github.com/stripe/react-stripe-elements/issues/256).

**Comment by electric-ladyland** [comment]
Just speculating right now, but something doesn't sit right with me on this issue. All these blockers have blocked something they identify as ad/tracking related... Assuming that's not in error, Stripe/Elements have been slimey to implement in such a way that core functionality (payment) is blocked! 

I don't use Ghostery so if you could handle that, I'll report to uBlock team and update this ticket.

**Comment by electric-ladyland** [comment]
@sambokai I just enabled my uBlock extension again to test it out. I'm just seeing HTTP requests against `https://q.stripe.com/?event=` blocked but the charge token was generated OK. Are you seeing different errors? I want to make sure I correctly report it to uBlock.

**Comment by sambokai** [comment]
@electric-ladyland 
Same for me:
<img width="1672" alt="bildschirmfoto 2019-01-29 um 18 52 35" src="https://user-images.githubusercontent.com/7689616/51944050-56c55280-241b-11e9-809d-ffde30427921.png">

I don't use Ghostery either, but it seems to work again.[ I tested 4 adblockers and ublock origin was the only blocked one.](https://github.com/stripe/react-stripe-elements/issues/314)

**Comment by electric-ladyland** [comment]
I'm going to close this then as doesn't look like we need to do anything. uBlock blocks some events but still works. Anyone feel free to reopen.
