### ISSUE TITLE
Module not already loaded loading "../../Observable"

### ISSUE THREAD

**Issue by imranmomin** [richnologies/ngx-stripe#6]
Hello @richnologies,  I'm getting the below error while loading the module using SystemJs.

```
localhost/:39 Error: Module not already loaded loading "../../Observable" as http://localhost/Observable.
  Evaluating http://localhost/node_modules/ngx-stripe/bundles/ngx-stripe.umd.js
  Evaluating http://localhost/scripts/app/app.module.js
  Evaluating http://localhost/scripts/app/boot.js
  Loading scripts/app
    at require (system.src.js:2868)
    at Object.eval (/node_modules/ngx-stripe/bundles/ngx-stripe.umd.js:7)
    at execute (system.src.js:2951)
    at dynamicExecute (system.src.js:1145)
    at doEvaluate (system.src.js:1092)
    at ensureEvaluate (system.src.js:1000)
    at system.src.js:1018
    at Object.eval (/scripts/app/app.module.js:15)
    at eval (/scripts/app/app.module.js:64)
    at eval (/scripts/app/app.module.js:65)
```
The issue is with loading `Observable`

**Comment by richnologies** [comment]
Hi, I push a new version, 0.2.2 where I try to fix the rollup rx imports. However I have no experience with SystemJS. So, I invite you to test this new version 0.2.2.

If it works we will close the issue. If not, I would appreciate very much if you could provide me with a good seed project to test SystemJS.

**Comment by imranmomin** [comment]
Thanks @richnologies, I will soon test and let you know

**Comment by imranmomin** [comment]
@richnologies, the new package does not raise any error while loading from SystemJS. 
I will close the issue.
