### ISSUE TITLE
PaymentIntents

### ISSUE THREAD

**Issue by balasphilip** [richnologies/ngx-stripe#62]
Hello. Thanks for great library.

Does it support PaymentIntents? Especially such methods as:
- stripe.retrievePaymentIntent()
- stripe.handleCardPayment()
- stripe.confirmPaymentIntent()

Didn't find it in the sources.

Thank you,
Regards.

**Comment by nickdnk** [comment]
I also gravely lack `stripe.createPaymentMethod()`. I've tried for an entire day to get it to work without modifying the library, but it seems to be impossible.

**Comment by richnologies** [comment]
merge #64. Please check it works as spected
