### ISSUE TITLE
Cant import

### ISSUE THREAD

**Issue by einewton** [richnologies/ngx-stripe#7]
I get this error following your instruction...

When I add this line I get the error:
NgxStripeModule.forRoot({
      apiKey: '***your-stripe-publishable key***'
    }),

Error:
Error	TS2345	(TS) Argument of type '{ apiKey: string; }' is not assignable to parameter of type 'string'.

Please help.
I am using Angular 4.4.4
with angular-cli

**Comment by richnologies** [comment]
Sorrry, docs were wrong. No need for the object, just pass the apiKey directly to the forRoot method. 

I update the readme, so you can check it there

**Comment by einewton** [comment]
Thank you so much for your support on this.  Please also update npmjs as that is where I originally got your example.
