### ISSUE TITLE
Angular 8

### ISSUE THREAD

**Issue by LoganDark** [richnologies/ngx-stripe#70]
```
npm WARN ngx-stripe@7.4.0 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-stripe@7.4.0 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
```

Latest version on NPM only wants Angular 7, but I updated to Angular 8.

I believe this should work fine, but I'm still raising the issue.

**Comment by dottodot** [comment]
This will be fixed by this PR https://github.com/richnologies/ngx-stripe/pull/69 just waiting on a decision on including Angular 6 or not.

**Comment by LoganDark** [comment]
What do you mean by "including Angular 6"?

I would retain compatibility with it. Angular 6 is only like one year ago.

**Comment by dottodot** [comment]
Read the PR, I'm referring to having it Angular 6 and above in the peer dependencies.It's currently 7 and above (or will be once merged)

**Comment by LoganDark** [comment]
@dottodot Yeah, that's what I mean.

**Comment by richnologies** [comment]
Thanks @dottodot for the PR. Finally I also include Angular 6

**Comment by nickdnk** [comment]
@richnologies I added a changelog, so you should remember to add your changes to `CHANGELOG.md` when releasing new versions. Otherwise it would be appropriate to remove that file entirely :)
