### ISSUE TITLE
How do I know if cvc card is being sent to stripe?

### ISSUE THREAD

**Issue by jkon** [richnologies/ngx-stripe#79]
This is really more of a question than a bug, depending on the answer I guess. How do I determine whether or not the cvc code that is in the stripe component is actually sent to stripe? I am passing the component to createToken form like this: 
``` 
@ViewChild( 'stripeCard', { static: false } ) stripeCard: StripeCardComponent;
...

this._stripeService.createToken( this.stripeCard.getCard(), this.cardForm.getRawValue() )
```

But I got an email from stripe yesterday that said none of my card payments are using the cvc code.
The stripe component seems to have a spot for it in the form, but according to stripe, it isn't being sent with the rest of the card info. When inspecting the stripeCard component in the debugger, I'm not seeing anything that helps me confirm the cvc code is present in the object getCard() returns
Thanks

**Comment by nickdnk** [comment]
Inspect the traffic in your browser and see if the CVC code is sent to Stripe’s servers when you tokenise the card.

On 14 Nov 2019, at 19.38, Joshua Kon <notifications@github.com<mailto:notifications@github.com>> wrote:


This is really more of a question than a bug, depending on the answer I guess. How do I determine whether or not the cvc code that is in the stripe component is actually sent to stripe? I am passing the component to createToken form like this:

@ViewChild( 'stripeCard', { static: false } ) stripeCard: StripeCardComponent;
...

this._stripeService.createToken( this.stripeCard.getCard(), this.cardForm.getRawValue() )


But I got an email from stripe yesterday that said none of my card payments are using the cvc code.
The stripe component seems to have a spot for it in the form, but according to stripe, it isn't being sent with the rest of the card info. When inspecting the stripeCard component in the debugger, I'm not seeing anything that helps me confirm the cvc code is present in the object getCard() returns
Thanks

**Comment by jkon** [comment]
@nickdnk great idea, thanks! It does seem to be in the form data sent to stripe. Now this is no longer an issue with ngx-stripe, so I'll close. But now I ahve no idea why stripe is telling me I'm not using the cvc
