### ISSUE TITLE
Feature Request - Able to change the key

### ISSUE THREAD

**Issue by einewton** [richnologies/ngx-stripe#8]
Hi @richnologies 

In my application there are many key's I use for my customers, but wanted to see if it exists or plans to add a way to change the Publishable key ?

Thanks again for all of your work on this!

**Comment by richnologies** [comment]
This feature was not on my use case, but I think it could be a nice one to have. 

Any suggestions on how would you like to use it? I mean, you will need to have more than one instance of the stripe object with different keys at the same time?

Would you be willing to help me test this feature?

**Comment by einewton** [comment]
I'll help test out the feature for sure!

Not more than one instance, but maybe a changeKey() method would be good.. 

That way if people want to toggle between the sandbox Publishable key and production they could easily call changeKey()

In my instance, I have a list of stripe keys in my database for each customer, and depending on who they are logged in as, I will need to load that companies key.

Thanks so much!

**Comment by daco** [comment]
Thanks for this module!
Apart from the above, it would be nice if you could change the stripeAccount as well.

Thanks

**Comment by crebuh** [comment]
Would be awesome to be able to change the key on the fly. For example in our system we have 3 environments. So it would be very helpful to just inject the key depending on the environment

**Comment by nukec** [comment]
@richnologies did you have luck implementing this?

**Comment by robermorales** [comment]
I also saw the `changeKey` method, but after getting an error I searched and found this issue.

Definitely I think @richnologies miss to push the package into npm.

Any plan to do it?

**Comment by richnologies** [comment]
Hi everyone, sorry for the delay, take a look at the StripeFactory in the readme, and tell me if it solves your case

**Comment by robermorales** [comment]
thanks!
