### ISSUE TITLE
Angular 9 Compatibility

### ISSUE THREAD

**Issue by alsoicode** [richnologies/ngx-stripe#83]
**Is this a feature request or a bug report?**
Bug Report

**What's gone wrong?**
After updating my project to Angular 9 and TypeScript 3.7.5, initializing the <ngx-stripe-card> component in my template is throwing this error:

![Screen Shot 2020-02-11 at 5 02 49 PM](https://user-images.githubusercontent.com/86738/74479134-a935ad80-4e7c-11ea-8da8-dca061c11d22.png)

**What was meant to happen?**
The `<ngx-stripe-card>` component should initialize without errors.

**Steps to reproduce**
Update your project to Angular 9 and TypeScript 3.7.5.
Install ngx-stripe version 7.4.4
Initialize an ngx-stripe-card instance.

**Other information**
My component instance is initially hidden via an `*ngIf` statement.

**Comment by bradyisom** [comment]
I have three instances of the ngx-stripe component in my Angular 9 application and ran into this same issue on all three of them. I was able to workaround two, but not the third. 

One of them, I had a `@ViewChild` reference to the component and fixed it by making it a non-static reference: 

`@ViewChild(StripeCardComponent, { static: false }) card: StripeCardComponent;`

The second one, I changed my `*ngIf` attribute to a `[hidden]` attribute to fix it. 

The third one, which I could not workaround, is in a dialog template that I dynamically show.

**Comment by bradyisom** [comment]
I think the could be fixed by changing line 35 of stripe-card.component.ts to be:

` @ViewChild('stripeCard', { static: false }) public stripeCard!: ElementRef;`

**Comment by bradyisom** [comment]
Actually, I tried tweaking that code without success. I think the real issue is that the `this.element.mount()` call needs to be made on or after `ngAfterViewInit` instead of inside `ngOnInit`

**Comment by richnologies** [comment]
Merge the PR and release new version

**Comment by alsoicode** [comment]
Thank you @richnologies
