### ISSUE TITLE
Emit not working

### ISSUE THREAD

**Issue by dwilson14** [richnologies/ngx-stripe#86]
Angular 7 dotnet core trying to access the change event on the ngx-strip-card element. I have the code added similar to the examples provided and the change event does not fire in my component. 
My HTML =>
            <ngx-stripe-card [options]="cardOptions" [elementsOptions]="elementsOptions" (change)="onChange($event)"></ngx-stripe-card>
Start of my component =>
import { StripeService, Element as StripeElement, StripeCardComponent, ElementOptions, ElementsOptions } from "ngx-stripe";
followed by
export class CartComponent implements OnInit, OnDestroy {
  //@ViewChild(StripeCardComponent) card: StripeCardComponent;

  error: any;
  complete = false;
  element: StripeElement; 
  cardOptions: ElementOptions = {...
and then the onChange method =>
onChange(result) {
    this.element = result.element;
    this.complete = result.card.complete;
    this.error = undefined;
  }

The purpose is to get the complete parameter to set my buy button disabled until the ngx-stripe-card element is complete.
Any advice or suggestions would be appreciated

**Comment by xinthose** [comment]
I have the same question.  I wish Stripe supported Angular as well as React.

**Comment by xinthose** [comment]
I figured it out, `Element` has an `on` method for detecting changes:

**element.d.ts**

```
export interface Element {
    mount(el: HTMLElement | string): void;
    on(ev: ElementEventType, handler: (ev?: any) => void): void;
    blur(): void;
    clear(): void;
    focus(): void;
    unmount(): void;
    update(options: ElementOptions): void;
}
```

After the card is mounted, you can check for errors and manually update your reactive form:

```
    this.stripe.elements(this.elementsOptions)
      .subscribe(elements => {
        this.elements = elements;
        // Only mount the element the first time
        if (!this.card) {
          this.card = this.elements.create('card', this.cardOptions);
          this.card.mount("#card-element");
          this.card.on("change", (result) => {
            if (this.debug) {
              this.logger.debug("NewCreditCardComponent >> card change = " + JSON.stringify(result));
            }

            // check for card errors
            if (result.error) {
              this.newCreditCardForm.setErrors({ cardError: true });
              this.cardErrorMsg = result.error.message;
            } else {
              if (this.newCreditCardForm.hasError("cardError")) {
                delete this.newCreditCardForm.errors.cardError;
                this.newCreditCardForm.updateValueAndValidity({ onlySelf: true});
              }
              this.cardErrorMsg = "";
            }
          })
        }
      });
```

**template**

```
<!-- Credit Card Error -->
<div class="row mt-2 justify-content-center">
    <div class="col">
        <div *ngIf="newCreditCardForm.errors?.cardError"
            class="cross-validation-error-message alert alert-danger">
            {{ cardErrorMsg }}
        </div>
    </div>
</div>   
```

**Comment by dwilson14** [comment]
Adam,
I found the same thing AND still had a scope issue - it may help others:
this.card.mount('#card-element');
var vm = this;
this.card.on('change', function ( event) {
            if (event.complete) {
              vm.notComplete = false; ...
hope that helps someone
