### ISSUE TITLE
Validate that all card info has been entered and enable Google autofill

### ISSUE THREAD

**Issue by tchpowdog** [richnologies/ngx-stripe#94]
We need a way of validating the card information has been entered.  I would like to disable the submit button until all card information has been entered.

Also, it would be nice if the user didn't see the following message when they click into the stripe-card
![stripeunsecure](https://user-images.githubusercontent.com/39231236/82760907-411c2f00-9dbc-11ea-8d99-accfba9ee674.png)

**Comment by Daggle24** [comment]
Your application has to use HTTPS in order to google auto fill the card field. It's exactly what is saying the message.

**Comment by kuldeeps1ngh** [comment]
> We need a way of validating the card information has been entered. I would like to disable the submit button until all card information has been entered.
> 
> Also, it would be nice if the user didn't see the following message when they click into the stripe-card
> ![stripeunsecure](https://user-images.githubusercontent.com/39231236/82760907-411c2f00-9dbc-11ea-8d99-accfba9ee674.png)

Have you found any solution for validate card information. I am also facing same issue.

**Comment by tchpowdog** [comment]
> > We need a way of validating the card information has been entered. I would like to disable the submit button until all card information has been entered.
> > Also, it would be nice if the user didn't see the following message when they click into the stripe-card
> > ![stripeunsecure](https://user-images.githubusercontent.com/39231236/82760907-411c2f00-9dbc-11ea-8d99-accfba9ee674.png)
> 
> Have you found any solution for validate card information. I am also facing same issue.

I have not.  My second issue was a misunderstanding on my part, I was running the app on localhost which isn't secure.  But I still do not know how to validate the card.

**Comment by xinthose** [comment]
When the card changes, check for errors.  When you submit the token server side to stripe, you will get errors if there are any.  
```
this.stripe.elements(this.elementsOptions)
.subscribe(elements => {
  this.elements = elements;
  // Only mount the element the first time
  if (!this.card) {
    this.card = this.elements.create('card', this.cardOptions);
    this.card.mount("#card-element");
    this.card.on("change", (result) => {
      if (this.debug) {
        this.logger.debug("NewCreditCardComponent >> card change = " + JSON.stringify(result));
      }

      // check for card errors
      if (result.error) {
        this.newCreditCardForm.setErrors({ cardError: true });
        this.cardErrorMsg = result.error.message;
      } else {
        if (this.newCreditCardForm.hasError("cardError")) {
          delete this.newCreditCardForm.errors!.cardError;
          this.newCreditCardForm.updateValueAndValidity({ onlySelf: true });
        }
        this.cardErrorMsg = "";
      }
    })
  }
});
```

**Comment by richnologies** [comment]
I will close this now due to inactivity. Sorry for this library to be abandon for such a long time. A new version of the library has been published that should address this issue. If the problem persists, please fell free to open it again. The new commitment of the team is to answer in less than a week. 

Please check this example on validation: https://richnologies.gitbook.io/ngx-stripe/examples#input-validation
